window.NEWS_DATA = [
  {
    "id": "https://ac24horas.com/2026/04/17/estaduais-sub-11-e-15-de-futsal-com-mais-6-partidas-no-lourenco-filho/",
    "slug": "estaduais-sub-11-e-15-de-futsal-com-mais-6-partidas-no-lourenco-filho",
    "title": "Estaduais Sub-11 e 15 de futsal com mais 6 partidas no Lourenço Filho",
    "summary": "Foto: Sueli Rodrigues -Torneios começaram com jogos bem equilibrados \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-20.25.03-300x202.jpeg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-20.25.03-1200x809.jpeg\" A primeira fase dos Estaduais Sub-11 e Sub-15 de futsal terão mais seis partidas neste sábado, 18, a partir das 13h45, na quadra do Instituto Lourenço Filho. “Não tivemos um espaço disponível no último fim de semana e por isso não promovemos as partidas. A quadra do Lourenço Filho surgiu como um alternativa”, comentou o [&#8230;]",
    "lede": "Foto: Sueli Rodrigues -Torneios começaram com jogos bem equilibrados \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-20.25.03-300x202.jpeg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-20.25.03-1200x809.jpeg\" A primeira fase dos Estaduais Sub-11 e Sub-15 de futsal terão mais seis partidas neste sábado, 18, a partir das 13h45, na quadra do Instituto Lourenço Filho. “Não tivemos um espaço disponível no último fim de semana e por isso não promovemos as partidas. A quadra do Lourenço Filho surgiu como um alternativa”, comentou o [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/estaduais-sub-11-e-15-de-futsal-com-mais-6-partidas-no-lourenco-filho/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/estaduais-sub-11-e-15-de-futsal-com-mais-6-partidas-no-lourenco-filho/",
    "sourceName": "ac24horas",
    "sourceLabel": "Estaduais Sub-11 e 15 de futsal com mais 6 partidas no Lourenço Filho",
    "category": "Esporte",
    "publishedAt": "2026-04-18T01:33:57.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-20.25.03-1200x809.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-20.25.03-1200x809.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-20.25.03-1200x809.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/dolar-fecha-em-r-498-no-menor-valor-do-ano-apos-ira-reabrir-ormuz/",
    "slug": "dolar-fecha-em-r-4-98-no-menor-valor-do-ano-apos-ira-reabrir-ormuz",
    "title": "Dólar fecha em R$ 4,98, no menor valor do ano, após Irã reabrir Ormuz",
    "summary": "Foto: Reuters/Nguyen Huy Kham \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/2026-02-26t200758z_1_lynxmpem1p1ak_rtroptp_4_dollar-hedging-bny-2-300x179.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/2026-02-26t200758z_1_lynxmpem1p1ak_rtroptp_4_dollar-hedging-bny-2.jpg\" O anúncio de que o Irã vai reabrir o Estreito de Ormuz pesou sobre o dólar nesta sexta-feira no Brasil, com a moeda norte-americana encerrando o dia no território negativo, renovando a menor cotação do ano. O dólar à vista encerrou o dia em leve queda de 0,20%, aos R$4,9836, menor valor de fechamento desde [&#8230;]",
    "lede": "Foto: Reuters/Nguyen Huy Kham \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/2026-02-26t200758z_1_lynxmpem1p1ak_rtroptp_4_dollar-hedging-bny-2-300x179.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/2026-02-26t200758z_1_lynxmpem1p1ak_rtroptp_4_dollar-hedging-bny-2.jpg\" O anúncio de que o Irã vai reabrir o Estreito de Ormuz pesou sobre o dólar nesta sexta-feira no Brasil, com a moeda norte-americana encerrando o dia no território negativo, renovando a menor cotação do ano. O dólar à vista encerrou o dia em leve queda de 0,20%, aos R$4,9836, menor valor de fechamento desde [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/dolar-fecha-em-r-498-no-menor-valor-do-ano-apos-ira-reabrir-ormuz/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/dolar-fecha-em-r-498-no-menor-valor-do-ano-apos-ira-reabrir-ormuz/",
    "sourceName": "ac24horas",
    "sourceLabel": "Dólar fecha em R$ 4,98, no menor valor do ano, após Irã reabrir Ormuz",
    "category": "Negócios",
    "publishedAt": "2026-04-18T00:34:20.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/2026-02-26t200758z_1_lynxmpem1p1ak_rtroptp_4_dollar-hedging-bny-2.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/2026-02-26t200758z_1_lynxmpem1p1ak_rtroptp_4_dollar-hedging-bny-2.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/213095711-km2d6r6bb5aabk44aiuilabpai-1200x799.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/deputada-michelle-melo-protocola-pl-que-propoe-piso-para-farmaceuticos-no-acre/",
    "slug": "deputada-michelle-melo-protocola-pl-que-propoe-piso-para-farmaceuticos-no-acre",
    "title": "Deputada Michelle Melo protocola PL que propõe piso para farmacêuticos no Acre",
    "summary": "Um projeto de lei de autoria da deputada Michelle Melo (União), que propõe a criação do piso salarial para farmacêuticos que atuam no Acre, foi protocolado nesta sexta-feira (17), na Assembleia Legislativa do Estado do Acre. Durante o ato de protocolização, a parlamentar destacou a importância da proposta para a valorização da categoria e a [&#8230;]",
    "lede": "Um projeto de lei de autoria da deputada Michelle Melo (União), que propõe a criação do piso salarial para farmacêuticos que atuam no Acre, foi protocolado nesta sexta-feira (17), na Assembleia Legislativa do Estado do Acre. Durante o ato de protocolização, a parlamentar destacou a importância da proposta para a valorização da categoria e a [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/deputada-michelle-melo-protocola-pl-que-propoe-piso-para-farmaceuticos-no-acre/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/deputada-michelle-melo-protocola-pl-que-propoe-piso-para-farmaceuticos-no-acre/",
    "sourceName": "ac24horas",
    "sourceLabel": "Deputada Michelle Melo protocola PL que propõe piso para farmacêuticos no Acre",
    "category": "Negócios",
    "publishedAt": "2026-04-17T23:53:07.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-18.47.02-1200x675.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-18.47.02-1200x675.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_5335-1200x800.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/mailza-da-posse-a-novos-professores-e-promete-avanco-na-educacao-publica/",
    "slug": "mailza-da-posse-a-novos-professores-e-promete-avanco-na-educacao-publica",
    "title": "Mailza dá posse a novos professores e promete avanço na educação pública",
    "summary": "Foto: Sérgio Vale/ac24horas \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-17.02.13-1-300x172.jpeg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-17.02.13-1-1200x687.jpeg\" A governadora do Acre, Mailza Assis Cameli, empossou nesta sexta-feira (17), 142 novos professores da rede pública estadual no quadro efetivo, durante cerimônia realizada no auditório do Detran, em Rio Branco. A solenidade marca a sexta convocação do concurso da Educação e reforça a política de ampliação e estruturação da rede estadual de ensino. Do [&#8230;]",
    "lede": "Foto: Sérgio Vale/ac24horas \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-17.02.13-1-300x172.jpeg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-17.02.13-1-1200x687.jpeg\" A governadora do Acre, Mailza Assis Cameli, empossou nesta sexta-feira (17), 142 novos professores da rede pública estadual no quadro efetivo, durante cerimônia realizada no auditório do Detran, em Rio Branco. A solenidade marca a sexta convocação do concurso da Educação e reforça a política de ampliação e estruturação da rede estadual de ensino. Do [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/mailza-da-posse-a-novos-professores-e-promete-avanco-na-educacao-publica/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/mailza-da-posse-a-novos-professores-e-promete-avanco-na-educacao-publica/",
    "sourceName": "ac24horas",
    "sourceLabel": "Mailza dá posse a novos professores e promete avanço na educação pública",
    "category": "Educação",
    "publishedAt": "2026-04-17T22:34:18.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-17.02.13-1-1200x687.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-17.02.13-1-1200x687.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-17.02.13-1200x726.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/no-acre-ex-merendeiro-e-empossado-como-professor-efetivo-com-muito-esforco/",
    "slug": "ex-merendeiro-e-empossado-como-professor-efetivo-8220-com-muito-esforco-8221",
    "title": "Ex-merendeiro é empossado como professor efetivo: &#8220;com muito esforço&#8221;",
    "summary": "A cerimônia de posse de novos servidores da educação estadual, realizada nesta sexta-feira (17), em Rio Branco, foi marcada não apenas pelos números da sexta convocação do concurso, mas por histórias que revelam o impacto direto da política pública na vida das pessoas. Entre os 142 empossados, a trajetória de Isaac Medeiros sintetiza o significado [&#8230;]",
    "lede": "A cerimônia de posse de novos servidores da educação estadual, realizada nesta sexta-feira (17), em Rio Branco, foi marcada não apenas pelos números da sexta convocação do concurso, mas por histórias que revelam o impacto direto da política pública na vida das pessoas. Entre os 142 empossados, a trajetória de Isaac Medeiros sintetiza o significado [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/no-acre-ex-merendeiro-e-empossado-como-professor-efetivo-com-muito-esforco/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/no-acre-ex-merendeiro-e-empossado-como-professor-efetivo-com-muito-esforco/",
    "sourceName": "ac24horas",
    "sourceLabel": "Ex-merendeiro é empossado como professor efetivo: &#8220;com muito esforço&#8221;",
    "category": "Educação",
    "publishedAt": "2026-04-17T22:21:41.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-17T172731.697.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-17T172731.697.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_5335-1200x800.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/mailza-nega-saida-de-donadoni-e-fala-em-fogo-amigo-no-governo/",
    "slug": "mailza-nega-saida-de-donadoni-e-fala-em-fogo-amigo-no-governo",
    "title": "Mailza nega saída de Donadoni e fala em “fogo amigo” no governo",
    "summary": "Foto: Sérgio Vale \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-17T171326.439-300x214.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-17T171326.439.jpg\" Em meio a especulações sobre mudanças no núcleo político do governo, a governadora do Acre, Mailza Assis, negou nesta sexta-feira (17) qualquer possibilidade de saída do secretário de Estado da Casa Civil, Jonathan Xavier Donadoni. A declaração foi dada durante coletiva de imprensa em Rio Branco, após a cerimônia de posse de novos professores efetivos [&#8230;]",
    "lede": "Foto: Sérgio Vale \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-17T171326.439-300x214.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-17T171326.439.jpg\" Em meio a especulações sobre mudanças no núcleo político do governo, a governadora do Acre, Mailza Assis, negou nesta sexta-feira (17) qualquer possibilidade de saída do secretário de Estado da Casa Civil, Jonathan Xavier Donadoni. A declaração foi dada durante coletiva de imprensa em Rio Branco, após a cerimônia de posse de novos professores efetivos [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/mailza-nega-saida-de-donadoni-e-fala-em-fogo-amigo-no-governo/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/mailza-nega-saida-de-donadoni-e-fala-em-fogo-amigo-no-governo/",
    "sourceName": "ac24horas",
    "sourceLabel": "Mailza nega saída de Donadoni e fala em “fogo amigo” no governo",
    "category": "Prefeitura",
    "publishedAt": "2026-04-17T22:04:43.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-17T171326.439.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-17T171326.439.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_5335-1200x800.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/no-acre-estreante-no-crime-e-preso-no-primeiro-dia-como-traficante/",
    "slug": "no-acre-estreante-no-crime-e-preso-no-primeiro-dia-como-traficante",
    "title": "No Acre, estreante no crime é preso no primeiro dia como traficante",
    "summary": "Pedro Paulo Crisóstomo, de 30 anos, se deu mal ao tentar ingressar no submundo do crime. Na noite de quinta-feira (16), depois de uma série de erros no seu primeiro dia de “trabalho”, foi preso por uma guarnição do Comando Tático do 3º Batalhão da Polícia Militar com cerca de 250g de maconha do tipo [&#8230;]",
    "lede": "Pedro Paulo Crisóstomo, de 30 anos, se deu mal ao tentar ingressar no submundo do crime. Na noite de quinta-feira (16), depois de uma série de erros no seu primeiro dia de “trabalho”, foi preso por uma guarnição do Comando Tático do 3º Batalhão da Polícia Militar com cerca de 250g de maconha do tipo [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/no-acre-estreante-no-crime-e-preso-no-primeiro-dia-como-traficante/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/no-acre-estreante-no-crime-e-preso-no-primeiro-dia-como-traficante/",
    "sourceName": "ac24horas",
    "sourceLabel": "No Acre, estreante no crime é preso no primeiro dia como traficante",
    "category": "Polícia",
    "publishedAt": "2026-04-17T22:01:18.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/7af67d1d-be2a-4956-bded-4d6feaeacb54-1200x970.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/7af67d1d-be2a-4956-bded-4d6feaeacb54-1200x970.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/bec1db27-14d4-4d33-9b3d-045deb114063-1200x713.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/mailza-promove-reuniao-com-prefeitos-e-reforca-parceria-com-municipios/",
    "slug": "mailza-promove-reuniao-com-prefeitos-e-reforca-parceria-com-municipios",
    "title": "Mailza promove reunião com prefeitos e reforça parceria com municípios",
    "summary": "A governadora do Acre, Mailza Assis (Progressistas), reuniu nesta sexta-feira, 17, prefeitos dos municípios acreanos em um encontro voltado ao diálogo institucional e ao alinhamento de ações conjuntas para o desenvolvimento do estado. A agenda foi divulgada pela própria gestora nas redes sociais, acompanhada de uma foto com os chefes dos Executivos municipais. De acordo [&#8230;]",
    "lede": "A governadora do Acre, Mailza Assis (Progressistas), reuniu nesta sexta-feira, 17, prefeitos dos municípios acreanos em um encontro voltado ao diálogo institucional e ao alinhamento de ações conjuntas para o desenvolvimento do estado. A agenda foi divulgada pela própria gestora nas redes sociais, acompanhada de uma foto com os chefes dos Executivos municipais. De acordo [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/mailza-promove-reuniao-com-prefeitos-e-reforca-parceria-com-municipios/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/mailza-promove-reuniao-com-prefeitos-e-reforca-parceria-com-municipios/",
    "sourceName": "ac24horas",
    "sourceLabel": "Mailza promove reunião com prefeitos e reforça parceria com municípios",
    "category": "Prefeitura",
    "publishedAt": "2026-04-17T21:57:23.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_5335-1200x800.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_5335-1200x800.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_5335-1200x800.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/paralisacao-deixa-passageiros-sem-onibus-por-horas-no-terminal-de-rio-branco/",
    "slug": "paralisacao-deixa-passageiros-sem-onibus-por-horas-no-terminal-de-rio-branco",
    "title": "Paralisação deixa passageiros sem ônibus por horas no terminal de Rio Branco",
    "summary": "Foto: David Medeiros \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/7f40348f-93b0-4f6e-82dc-9edb0ecda3cd-300x169.jpeg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/7f40348f-93b0-4f6e-82dc-9edb0ecda3cd-1200x675.jpeg\" A paralisação dos motoristas do transporte coletivo em Rio Branco causou transtornos a milhares de passageiros nesta sexta-feira (17). O movimento, organizado pelo Sindicato dos Trabalhadores em Transporte Público do Acre (SINTTPAC), teve início na quarta-feira (15), com cerca de 30% dos veículos fora de circulação. Na quarta-feira (15), a paralisação ocorreu de forma escalonada. [&#8230;]",
    "lede": "Foto: David Medeiros \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/7f40348f-93b0-4f6e-82dc-9edb0ecda3cd-300x169.jpeg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/7f40348f-93b0-4f6e-82dc-9edb0ecda3cd-1200x675.jpeg\" A paralisação dos motoristas do transporte coletivo em Rio Branco causou transtornos a milhares de passageiros nesta sexta-feira (17). O movimento, organizado pelo Sindicato dos Trabalhadores em Transporte Público do Acre (SINTTPAC), teve início na quarta-feira (15), com cerca de 30% dos veículos fora de circulação. Na quarta-feira (15), a paralisação ocorreu de forma escalonada. [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/paralisacao-deixa-passageiros-sem-onibus-por-horas-no-terminal-de-rio-branco/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/paralisacao-deixa-passageiros-sem-onibus-por-horas-no-terminal-de-rio-branco/",
    "sourceName": "ac24horas",
    "sourceLabel": "Paralisação deixa passageiros sem ônibus por horas no terminal de Rio Branco",
    "category": "Negócios",
    "publishedAt": "2026-04-17T21:07:58.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/7f40348f-93b0-4f6e-82dc-9edb0ecda3cd-1200x675.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/7f40348f-93b0-4f6e-82dc-9edb0ecda3cd-1200x675.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/7f40348f-93b0-4f6e-82dc-9edb0ecda3cd-1200x675.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/xapuri-decreta-situacao-de-emergencia-apos-fortes-chuvas-atingirem-alto-acre/",
    "slug": "xapuri-decreta-situacao-de-emergencia-apos-fortes-chuvas-atingirem-alto-acre",
    "title": "Xapuri decreta situação de emergência após fortes chuvas atingirem Alto Acre",
    "summary": "A Prefeitura de Xapuri decretou, nesta sexta-feira (17), situação de emergência nas áreas atingidas pelas fortes chuvas que castigaram o município na última quinta-feira (16). A medida foi oficializada por meio do Decreto nº 064/2026 e tem validade de 180 dias. De acordo com o decreto, o volume de chuva chegou a 76 milímetros em [&#8230;]",
    "lede": "A Prefeitura de Xapuri decretou, nesta sexta-feira (17), situação de emergência nas áreas atingidas pelas fortes chuvas que castigaram o município na última quinta-feira (16). A medida foi oficializada por meio do Decreto nº 064/2026 e tem validade de 180 dias. De acordo com o decreto, o volume de chuva chegou a 76 milímetros em [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/xapuri-decreta-situacao-de-emergencia-apos-fortes-chuvas-atingirem-alto-acre/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/xapuri-decreta-situacao-de-emergencia-apos-fortes-chuvas-atingirem-alto-acre/",
    "sourceName": "ac24horas",
    "sourceLabel": "Xapuri decreta situação de emergência após fortes chuvas atingirem Alto Acre",
    "category": "Utilidade Pública",
    "publishedAt": "2026-04-17T21:03:09.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/chuvas-em-xapuri.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/chuvas-em-xapuri.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-09-as-11.54.54_97faa9e2-1200x675.webp"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/usuarios-do-transporte-coletivo-da-capital-reclamam-da-paralizacao-feita-pelos-motoristas/",
    "slug": "usuarios-do-transporte-coletivo-da-capital-reclamam-da-paralizacao-feita-pelos-motoristas",
    "title": "Usuários do transporte coletivo da capital reclamam da paralização feita pelos motoristas",
    "summary": "Usuários do transporte coletivo enfrentaram horas de espera e superlotação no terminal urbano de Rio Branco devido à paralisação de motoristas por atraso salarial. Passageiros relataram falta de informação, cancelamento de viagens e dificuldades para retornar para casa, especialmente idosos, crianças e pessoas com necessidades especiais. A usuária Maria Liberdade afirmou ter aguardado por mais [&#8230;]",
    "lede": "Usuários do transporte coletivo enfrentaram horas de espera e superlotação no terminal urbano de Rio Branco devido à paralisação de motoristas por atraso salarial. Passageiros relataram falta de informação, cancelamento de viagens e dificuldades para retornar para casa, especialmente idosos, crianças e pessoas com necessidades especiais. A usuária Maria Liberdade afirmou ter aguardado por mais [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/usuarios-do-transporte-coletivo-da-capital-reclamam-da-paralizacao-feita-pelos-motoristas/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/usuarios-do-transporte-coletivo-da-capital-reclamam-da-paralizacao-feita-pelos-motoristas/",
    "sourceName": "ac24horas",
    "sourceLabel": "Usuários do transporte coletivo da capital reclamam da paralização feita pelos motoristas",
    "category": "Cultura",
    "publishedAt": "2026-04-17T20:48:40.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-15.43.05-1.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-15.43.05-1.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-15.43.05-1-1200x686.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/saida-de-marcio-expoe-ruidos-internos-e-testa-articulacao-politica-de-mailza/",
    "slug": "saida-de-marcio-expoe-ruidos-internos-e-testa-articulacao-politica-de-mailza",
    "title": "Saída de Márcio expõe ruídos internos e testa articulação política de Mailza",
    "summary": "Durante o programa Boa Conversa, apresentado pelos jornalistas Marcos Venícios, Astério Moreira e Crica avaliaram a saída do ex-secretário adjunto de governo Márcio Pereira, considerada um movimento que gerou desgaste político após críticas públicas à governadora Mailza Assis Cameli. Apesar de reconhecerem a capacidade de articulação de Márcio, os comentaristas afirmaram que ele não detinha [&#8230;]",
    "lede": "Durante o programa Boa Conversa, apresentado pelos jornalistas Marcos Venícios, Astério Moreira e Crica avaliaram a saída do ex-secretário adjunto de governo Márcio Pereira, considerada um movimento que gerou desgaste político após críticas públicas à governadora Mailza Assis Cameli. Apesar de reconhecerem a capacidade de articulação de Márcio, os comentaristas afirmaram que ele não detinha [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/saida-de-marcio-expoe-ruidos-internos-e-testa-articulacao-politica-de-mailza/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/saida-de-marcio-expoe-ruidos-internos-e-testa-articulacao-politica-de-mailza/",
    "sourceName": "ac24horas",
    "sourceLabel": "Saída de Márcio expõe ruídos internos e testa articulação política de Mailza",
    "category": "Cultura",
    "publishedAt": "2026-04-17T20:33:08.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-15-22-49-1.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-15-22-49-1.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-15-22-49-1-1200x686.jpg"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/governo-mailza-passa-por-ajustes-internos-e-busca-acomodacao-politica-entre-aliados/",
    "slug": "governo-mailza-passa-por-ajustes-internos-e-busca-acomodacao-politica-entre-aliados",
    "title": "Governo Mailza passa por ajustes internos e busca acomodação política entre aliados",
    "summary": "Durante análise no programa Boa Conversa, apresentado pelos jornalistas Marcos Venícios, Astério Moreira e Crica, comentaristas avaliaram que o início da gestão da governadora Mailza Assis Cameli ainda passa por um processo natural de acomodação política e administrativa. Segundo os jornalistas, nomes estratégicos do governo, como Luiz Calixto, adotam postura discreta enquanto a equipe se [&#8230;]",
    "lede": "Durante análise no programa Boa Conversa, apresentado pelos jornalistas Marcos Venícios, Astério Moreira e Crica, comentaristas avaliaram que o início da gestão da governadora Mailza Assis Cameli ainda passa por um processo natural de acomodação política e administrativa. Segundo os jornalistas, nomes estratégicos do governo, como Luiz Calixto, adotam postura discreta enquanto a equipe se [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/governo-mailza-passa-por-ajustes-internos-e-busca-acomodacao-politica-entre-aliados/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/governo-mailza-passa-por-ajustes-internos-e-busca-acomodacao-politica-entre-aliados/",
    "sourceName": "ac24horas",
    "sourceLabel": "Governo Mailza passa por ajustes internos e busca acomodação política entre aliados",
    "category": "Cultura",
    "publishedAt": "2026-04-17T20:31:47.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-15-22-49.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-15-22-49.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-15-22-49-1200x686.jpg"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/paris-garden-recebe-noite-de-mpb-e-dj-nesta-sexta-2/",
    "slug": "paris-garden-recebe-noite-de-mpb-e-dj-nesta-sexta",
    "title": "Paris Garden recebe noite de MPB e DJ nesta sexta",
    "summary": "O Paris Garden, em Rio Branco, recebe nesta sexta-feira (17) uma noite especial com a dupla formada pelo músico Álamo Kário e o Dj Felipe de Paula. O evento combina apresentação ao vivo de MPB com sets de música eletrônica. O espaço de entretenimento fica localizado na Av. Getúlio Vargas, 1832, no bairro Bosque, A [&#8230;]",
    "lede": "O Paris Garden, em Rio Branco, recebe nesta sexta-feira (17) uma noite especial com a dupla formada pelo músico Álamo Kário e o Dj Felipe de Paula. O evento combina apresentação ao vivo de MPB com sets de música eletrônica. O espaço de entretenimento fica localizado na Av. Getúlio Vargas, 1832, no bairro Bosque, A [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/paris-garden-recebe-noite-de-mpb-e-dj-nesta-sexta-2/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/paris-garden-recebe-noite-de-mpb-e-dj-nesta-sexta-2/",
    "sourceName": "ac24horas",
    "sourceLabel": "Paris Garden recebe noite de MPB e DJ nesta sexta",
    "category": "Negócios",
    "publishedAt": "2026-04-17T20:22:34.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/5358129b-6834-493a-be0d-b31933a06f2c.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/5358129b-6834-493a-be0d-b31933a06f2c.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2025-05-01-at-02.01.35-4-1200x800.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/oscar-schmidt-lenda-do-basquete-brasileiro-morre-aos-68-anos/",
    "slug": "oscar-schmidt-lenda-do-basquete-brasileiro-morre-aos-68-anos-de-idade",
    "title": "Oscar Schmidt, lenda do basquete brasileiro, morre aos 68 anos de idade",
    "summary": "Oscar Schmidt travava uma luta contra um câncer no cérebro há 11 anos Foto: Clayton de Souza/ Estadão / Estadão \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/213095711-km2d6r6bb5aabk44aiuilabpai-300x200.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/213095711-km2d6r6bb5aabk44aiuilabpai-1200x799.webp\" Oscar Schmidt, um dos maiores nomes da história do basquete brasileiro e mundial, morreu nesta sexta-feira, 17, aos 68 anos, em São Paulo. O ‘Mão Santa’ passou mal e foi levado para Hospital e Maternidade Municipal Santa Ana (HMSA), em Santana do Parnaíba, mas não resistiu. &#8220;É com profundo pesar que comunicamos o falecimento de Oscar [&#8230;]",
    "lede": "Oscar Schmidt travava uma luta contra um câncer no cérebro há 11 anos Foto: Clayton de Souza/ Estadão / Estadão \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/213095711-km2d6r6bb5aabk44aiuilabpai-300x200.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/213095711-km2d6r6bb5aabk44aiuilabpai-1200x799.webp\" Oscar Schmidt, um dos maiores nomes da história do basquete brasileiro e mundial, morreu nesta sexta-feira, 17, aos 68 anos, em São Paulo. O ‘Mão Santa’ passou mal e foi levado para Hospital e Maternidade Municipal Santa Ana (HMSA), em Santana do Parnaíba, mas não resistiu. &#8220;É com profundo pesar que comunicamos o falecimento de Oscar [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/oscar-schmidt-lenda-do-basquete-brasileiro-morre-aos-68-anos/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/oscar-schmidt-lenda-do-basquete-brasileiro-morre-aos-68-anos/",
    "sourceName": "ac24horas",
    "sourceLabel": "Oscar Schmidt, lenda do basquete brasileiro, morre aos 68 anos de idade",
    "category": "Saúde",
    "publishedAt": "2026-04-17T20:20:55.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/213095711-km2d6r6bb5aabk44aiuilabpai-1200x799.webp",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/213095711-km2d6r6bb5aabk44aiuilabpai-1200x799.webp",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/213095711-km2d6r6bb5aabk44aiuilabpai-1200x799.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/fe-na-missao-fest-music-reune-mais-de-16-igrejas-e-seis-bandas-neste-sabado-na-gameleira/",
    "slug": "fe-na-missao-fest-music-reune-mais-de-16-igrejas-e-seis-bandas-neste-sabado-na-gameleira",
    "title": "Fé na Missão Fest Music reúne mais de 16 igrejas e seis bandas neste sábado na Gameleira",
    "summary": "Foto: David Medeiros \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-14.42.36-2-300x169.jpeg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-14.42.36-2-1200x675.jpeg\" Um evento voltado ao público evangélico promete movimentar a Gameleira, em Rio Branco, neste sábado, a partir das 17h. O “Fé na Missão Fest Music” reunirá mais de 16 igrejas, seis bandas, DJ, além de praça de alimentação com comidas típicas, espaço para crianças e estrutura com tendas e camarins para os artistas. A iniciativa [&#8230;]",
    "lede": "Foto: David Medeiros \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-14.42.36-2-300x169.jpeg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-14.42.36-2-1200x675.jpeg\" Um evento voltado ao público evangélico promete movimentar a Gameleira, em Rio Branco, neste sábado, a partir das 17h. O “Fé na Missão Fest Music” reunirá mais de 16 igrejas, seis bandas, DJ, além de praça de alimentação com comidas típicas, espaço para crianças e estrutura com tendas e camarins para os artistas. A iniciativa [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/fe-na-missao-fest-music-reune-mais-de-16-igrejas-e-seis-bandas-neste-sabado-na-gameleira/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/fe-na-missao-fest-music-reune-mais-de-16-igrejas-e-seis-bandas-neste-sabado-na-gameleira/",
    "sourceName": "ac24horas",
    "sourceLabel": "Fé na Missão Fest Music reúne mais de 16 igrejas e seis bandas neste sábado na Gameleira",
    "category": "Cotidiano",
    "publishedAt": "2026-04-17T20:16:35.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-14.42.36-2-1200x675.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-14.42.36-2-1200x675.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-14.42.36-2-1200x675.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/partidas-da-2a-copa-acre-irao-decidir-mais-dois-semifinalistas/",
    "slug": "partidas-da-2-copa-acre-irao-decidir-mais-dois-semifinalistas",
    "title": "Partidas da 2ª Copa Acre irão decidir mais dois semifinalistas",
    "summary": "Foto Sueli Rodrigues: Semifinais da 2 Copa Acre serão disputadas no dia 24 \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-14-40-58-300x293.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-14-40-58-1200x1170.jpg\" A última rodada da fase de classificação da 2ª Copa Acre Sub-13 terá mais quatro partidas neste sábado, 18, no Tonicão, no CT do Cupuaçu e na Arena da Floresta. Jogos do grupo A O Santa Cruz, classificado para semifinal, enfrenta COPMBM, a partir das 8h30, no CT do Cupuaçu e joga para manter os [&#8230;]",
    "lede": "Foto Sueli Rodrigues: Semifinais da 2 Copa Acre serão disputadas no dia 24 \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-14-40-58-300x293.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-14-40-58-1200x1170.jpg\" A última rodada da fase de classificação da 2ª Copa Acre Sub-13 terá mais quatro partidas neste sábado, 18, no Tonicão, no CT do Cupuaçu e na Arena da Floresta. Jogos do grupo A O Santa Cruz, classificado para semifinal, enfrenta COPMBM, a partir das 8h30, no CT do Cupuaçu e joga para manter os [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/partidas-da-2a-copa-acre-irao-decidir-mais-dois-semifinalistas/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/partidas-da-2a-copa-acre-irao-decidir-mais-dois-semifinalistas/",
    "sourceName": "ac24horas",
    "sourceLabel": "Partidas da 2ª Copa Acre irão decidir mais dois semifinalistas",
    "category": "Esporte",
    "publishedAt": "2026-04-17T20:03:50.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-14-40-58-1200x1170.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-14-40-58-1200x1170.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-14-40-58-1200x1170.jpg"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/incra-amplia-para-122-familias-assentamento-entre-tarauaca-e-feijo/",
    "slug": "incra-amplia-para-122-familias-assentamento-entre-tarauaca-e-feijo",
    "title": "Incra amplia para 122 famílias assentamento entre Tarauacá e Feijó",
    "summary": "Foto: Jardy Lopes \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-09-as-11.54.54_97faa9e2-300x169.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-09-as-11.54.54_97faa9e2-1200x675.webp\" O Instituto Nacional de Colonização e Reforma Agrária (Incra) publicou nesta sexta-feira, 17, a Portaria nº 1.775, alterando a capacidade de atendimento do Projeto de Desenvolvimento Sustentável Acaraú, localizado nos municípios de Tarauacá e Feijó. O ato atualiza o número de famílias beneficiadas pelo assentamento criado no início deste ano. Com a mudança, a capacidade [&#8230;]",
    "lede": "Foto: Jardy Lopes \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-09-as-11.54.54_97faa9e2-300x169.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-09-as-11.54.54_97faa9e2-1200x675.webp\" O Instituto Nacional de Colonização e Reforma Agrária (Incra) publicou nesta sexta-feira, 17, a Portaria nº 1.775, alterando a capacidade de atendimento do Projeto de Desenvolvimento Sustentável Acaraú, localizado nos municípios de Tarauacá e Feijó. O ato atualiza o número de famílias beneficiadas pelo assentamento criado no início deste ano. Com a mudança, a capacidade [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/incra-amplia-para-122-familias-assentamento-entre-tarauaca-e-feijo/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/incra-amplia-para-122-familias-assentamento-entre-tarauaca-e-feijo/",
    "sourceName": "ac24horas",
    "sourceLabel": "Incra amplia para 122 famílias assentamento entre Tarauacá e Feijó",
    "category": "Saúde",
    "publishedAt": "2026-04-17T19:57:20.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-09-as-11.54.54_97faa9e2-1200x675.webp",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-09-as-11.54.54_97faa9e2-1200x675.webp",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2024/09/imagem-ilustrativa-abuso-estupro-agressao-violencia-contra-criancas-e-adolescentes-1600269547386_v2_1920x1280-1536x1024.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/chuvas-causam-transbordamento-de-igarape-e-interditam-trecho-da-br-364/",
    "slug": "chuvas-causam-transbordamento-de-igarape-e-interditam-trecho-da-br-364",
    "title": "Chuvas causam transbordamento de igarapé e interditam trecho da BR-364",
    "summary": "A rodovia BR-364 foi interditada parcialmente nesta sexta-feira (17), no trecho que liga Jaru a Ariquemes, em Rondônia. As fortes chuvas que atingiram a região nas últimas horas causaram o transbordamento de um igarapé que corta a rodovia federal. A força da água invadiu a pista e tornou a travessia extremamente perigosa, especialmente para veículos [&#8230;]",
    "lede": "A rodovia BR-364 foi interditada parcialmente nesta sexta-feira (17), no trecho que liga Jaru a Ariquemes, em Rondônia. As fortes chuvas que atingiram a região nas últimas horas causaram o transbordamento de um igarapé que corta a rodovia federal. A força da água invadiu a pista e tornou a travessia extremamente perigosa, especialmente para veículos [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/chuvas-causam-transbordamento-de-igarape-e-interditam-trecho-da-br-364/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/chuvas-causam-transbordamento-de-igarape-e-interditam-trecho-da-br-364/",
    "sourceName": "ac24horas",
    "sourceLabel": "Chuvas causam transbordamento de igarapé e interditam trecho da BR-364",
    "category": "Utilidade Pública",
    "publishedAt": "2026-04-17T19:43:15.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-13-54-06.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-13-54-06.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2024/09/imagem-ilustrativa-abuso-estupro-agressao-violencia-contra-criancas-e-adolescentes-1600269547386_v2_1920x1280-1536x1024.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/crianca-indigena-de-4-anos-cai-de-canoa-e-desaparece-no-rio-purus/",
    "slug": "crianca-indigena-de-4-anos-cai-de-canoa-e-desaparece-no-rio-purus",
    "title": "Criança indígena de 4 anos cai de canoa e desaparece no Rio Purus",
    "summary": "Foto: Mizael Louzada \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-10-as-10.47.18_01ba5c88-300x169.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-10-as-10.47.18_01ba5c88-1200x675.webp\" Uma criança indígena de 4 anos caiu de uma canoa e desapareceu no rio Purus na quinta-feira (16), em área próxima ao município de Santa Rosa do Purus, no interior do Acre. A vítima viajava com os pais no momento do acidente. De acordo com as primeiras informações, a embarcação foi atingida por um objeto [&#8230;]",
    "lede": "Foto: Mizael Louzada \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-10-as-10.47.18_01ba5c88-300x169.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-10-as-10.47.18_01ba5c88-1200x675.webp\" Uma criança indígena de 4 anos caiu de uma canoa e desapareceu no rio Purus na quinta-feira (16), em área próxima ao município de Santa Rosa do Purus, no interior do Acre. A vítima viajava com os pais no momento do acidente. De acordo com as primeiras informações, a embarcação foi atingida por um objeto [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/crianca-indigena-de-4-anos-cai-de-canoa-e-desaparece-no-rio-purus/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/crianca-indigena-de-4-anos-cai-de-canoa-e-desaparece-no-rio-purus/",
    "sourceName": "ac24horas",
    "sourceLabel": "Criança indígena de 4 anos cai de canoa e desaparece no Rio Purus",
    "category": "Negócios",
    "publishedAt": "2026-04-17T19:42:03.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-10-as-10.47.18_01ba5c88-1200x675.webp",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-10-as-10.47.18_01ba5c88-1200x675.webp",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2024/09/imagem-ilustrativa-abuso-estupro-agressao-violencia-contra-criancas-e-adolescentes-1600269547386_v2_1920x1280-1536x1024.avif"
  },
  {
    "id": "https://agencia.ac.gov.br/governadora-mailza-empossa-142-novos-servidores-e-reforca-rede-estadual-de-ensino/",
    "slug": "governadora-mailza-empossa-142-novos-servidores-e-reforca-rede-estadual-de-ensino",
    "title": "Governadora Mailza empossa 142 novos servidores e reforça rede estadual de ensino",
    "summary": "“Se a educação sozinha não transforma a sociedade, sem ela tampouco a sociedade muda”. Com a frase do emblemático educador Paulo Freire, a professora Franciane Leite encerrou seu discurso de agradecimento durante a sexta cerimônia de convocação de novos professores e servidores de apoio administrativo da rede estadual de ensino. O evento foi realizado na [&#8230;] The post Governadora Mailza empossa 142 novos servidores e reforça rede estadual de ensino appeared first on Noticias do Acre .",
    "lede": "“Se a educação sozinha não transforma a sociedade, sem ela tampouco a sociedade muda”. Com a frase do emblemático educador Paulo Freire, a professora Franciane Leite encerrou seu discurso de agradecimento durante a sexta cerimônia de convocação de novos professores e servidores de apoio administrativo da rede estadual de ensino. O evento foi realizado na [&#8230;] The post Governadora Mailza empossa 142 novos servidores e reforça rede estadual de ensino appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/governadora-mailza-empossa-142-novos-servidores-e-reforca-rede-estadual-de-ensino/",
    "sourceUrl": "https://agencia.ac.gov.br/governadora-mailza-empossa-142-novos-servidores-e-reforca-rede-estadual-de-ensino/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Governadora Mailza empossa 142 novos servidores e reforça rede estadual de ensino",
    "category": "Educação",
    "publishedAt": "2026-04-18T00:39:24.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/Ingrid-Kelly-Posse-Educacao-Mailza-Assis-9-1024x683.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/Ingrid-Kelly-Posse-Educacao-Mailza-Assis-9-1024x683.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/f908aa34-95be-4dcf-81a1-3aa1c4d4b739-1024x681.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/eu-sonho-em-transformar-a-vida-dos-estudantes-diz-professora-empossada-no-concurso-da-educacao/",
    "slug": "8216-eu-sonho-em-transformar-a-vida-dos-estudantes-8217-diz-professora-empossada-no-concurso-da-educacao",
    "title": "&#8216;Eu sonho em transformar a vida dos estudantes&#8217;, diz professora empossada no concurso da Educação",
    "summary": "O governo do Acre prossegue com o objetivo de fortalecer a educação de base, e reforçar o quadro efetivo de servidores do Estado em mais uma cerimônia de posse do maior concurso da história da educação. Nesta sexta-feira, 17, no auditório do Departamento Estadual de Trânsito (Detran) mais 142 servidores passam a ingressar o quadro [&#8230;] The post &#8216;Eu sonho em transformar a vida dos estudantes&#8217;, diz professora empossada no concurso da Educação appeared first on Noticias do Acre .",
    "lede": "O governo do Acre prossegue com o objetivo de fortalecer a educação de base, e reforçar o quadro efetivo de servidores do Estado em mais uma cerimônia de posse do maior concurso da história da educação. Nesta sexta-feira, 17, no auditório do Departamento Estadual de Trânsito (Detran) mais 142 servidores passam a ingressar o quadro [&#8230;] The post &#8216;Eu sonho em transformar a vida dos estudantes&#8217;, diz professora empossada no concurso da Educação appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/eu-sonho-em-transformar-a-vida-dos-estudantes-diz-professora-empossada-no-concurso-da-educacao/",
    "sourceUrl": "https://agencia.ac.gov.br/eu-sonho-em-transformar-a-vida-dos-estudantes-diz-professora-empossada-no-concurso-da-educacao/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "&#8216;Eu sonho em transformar a vida dos estudantes&#8217;, diz professora empossada no concurso da Educação",
    "category": "Educação",
    "publishedAt": "2026-04-17T22:56:02.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/d3f0666a-5405-4136-adbd-256b7ed02633-1024x637.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/d3f0666a-5405-4136-adbd-256b7ed02633-1024x637.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/594a65ab-4157-421d-8016-6efaa5f82c4b-1024x682.jpg"
  },
  {
    "id": "https://agencia.ac.gov.br/governadora-mailza-reune-prefeitos-do-acre-e-reforca-apoio-do-estado-as-gestoes-municipais/",
    "slug": "governadora-mailza-reune-prefeitos-do-acre-e-reforca-apoio-do-estado-as-gestoes-municipais",
    "title": "Governadora Mailza reúne prefeitos do Acre e reforça apoio do Estado às gestões municipais",
    "summary": "A governadora Mailza Assis recebeu, nesta sexta-feira, 16, no Palácio Rio Branco, prefeitos de municípios acreanos para reafirmar o compromisso do governo com o fortalecimento das gestões municipais e a ampliação do apoio institucional às administrações locais. O encontro reforçou a importância da parceria entre o Estado e os municípios para garantir avanços em áreas [&#8230;] The post Governadora Mailza reúne prefeitos do Acre e reforça apoio do Estado às gestões municipais appeared first on Noticias do Acre .",
    "lede": "A governadora Mailza Assis recebeu, nesta sexta-feira, 16, no Palácio Rio Branco, prefeitos de municípios acreanos para reafirmar o compromisso do governo com o fortalecimento das gestões municipais e a ampliação do apoio institucional às administrações locais. O encontro reforçou a importância da parceria entre o Estado e os municípios para garantir avanços em áreas [&#8230;] The post Governadora Mailza reúne prefeitos do Acre e reforça apoio do Estado às gestões municipais appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/governadora-mailza-reune-prefeitos-do-acre-e-reforca-apoio-do-estado-as-gestoes-municipais/",
    "sourceUrl": "https://agencia.ac.gov.br/governadora-mailza-reune-prefeitos-do-acre-e-reforca-apoio-do-estado-as-gestoes-municipais/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Governadora Mailza reúne prefeitos do Acre e reforça apoio do Estado às gestões municipais",
    "category": "Prefeitura",
    "publishedAt": "2026-04-17T22:38:25.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/bdf41f2c-94bd-4e97-b1c3-48e409f1b3e8-1024x682.jpg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/bdf41f2c-94bd-4e97-b1c3-48e409f1b3e8-1024x682.jpg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/f908aa34-95be-4dcf-81a1-3aa1c4d4b739-1024x681.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/policia-civil-reforca-delegacia-de-investigacoes-criminais-com-nova-viatura-e-alinhamento-estrategico/",
    "slug": "policia-civil-reforca-delegacia-de-investigacoes-criminais-com-nova-viatura-e-alinhamento-estrategico",
    "title": "Polícia Civil reforça Delegacia de Investigações Criminais com nova viatura e alinhamento estratégico",
    "summary": "A distribuição de uma viatura caracterizada trará reforço às ações da Divisão Especializada de Investigações Criminais (Deic), conforme ficou definido durante reunião de alinhamento promovida pela direção da Polícia Civil do Acre (PCAC), nesta sexta, 17 de abril, em Rio Branco. O encontro foi conduzido pelo delegado-geral, Pedro Buzolin, ao lado do delegado-geral adjunto, Martin [&#8230;] The post Polícia Civil reforça Delegacia de Investigações Criminais com nova viatura e alinhamento estratégico appeared first on Noticias do Acre .",
    "lede": "A distribuição de uma viatura caracterizada trará reforço às ações da Divisão Especializada de Investigações Criminais (Deic), conforme ficou definido durante reunião de alinhamento promovida pela direção da Polícia Civil do Acre (PCAC), nesta sexta, 17 de abril, em Rio Branco. O encontro foi conduzido pelo delegado-geral, Pedro Buzolin, ao lado do delegado-geral adjunto, Martin [&#8230;] The post Polícia Civil reforça Delegacia de Investigações Criminais com nova viatura e alinhamento estratégico appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/policia-civil-reforca-delegacia-de-investigacoes-criminais-com-nova-viatura-e-alinhamento-estrategico/",
    "sourceUrl": "https://agencia.ac.gov.br/policia-civil-reforca-delegacia-de-investigacoes-criminais-com-nova-viatura-e-alinhamento-estrategico/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Polícia Civil reforça Delegacia de Investigações Criminais com nova viatura e alinhamento estratégico",
    "category": "Polícia",
    "publishedAt": "2026-04-17T22:02:38.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/ABRE-MATERIA-DA-CIVIL-1-1024x682.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/ABRE-MATERIA-DA-CIVIL-1-1024x682.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-16.39.07-1-1024x683.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/governo-do-acre-busca-pactuacao-para-fortalecer-integracao-fisica-entre-brasil-e-peru-com-acesso-por-cruzeiro-do-sul/",
    "slug": "governo-do-acre-busca-pactuacao-para-fortalecer-integracao-fisica-entre-brasil-e-peru-com-acesso-por-cruzeiro-do-sul",
    "title": "Governo do Acre busca pactuação para fortalecer integração física entre Brasil e Peru, com acesso por Cruzeiro do Sul",
    "summary": "A ligação terrestre entre Cruzeiro do Sul, no Acre, e Pucallpa, capital do Departamento de Ucayali, pode se tornar realidade a partir de um acordo internacional entre Brasil e Peru, proposto pelo governo do Acre, com a anuência do Ministério das Relações Exteriores (MRE). Essa foi uma das propostas feitas por representantes do governo acreano, [&#8230;] The post Governo do Acre busca pactuação para fortalecer integração física entre Brasil e Peru, com acesso por Cruzeiro do Sul appeared first on Noticias do Acre .",
    "lede": "A ligação terrestre entre Cruzeiro do Sul, no Acre, e Pucallpa, capital do Departamento de Ucayali, pode se tornar realidade a partir de um acordo internacional entre Brasil e Peru, proposto pelo governo do Acre, com a anuência do Ministério das Relações Exteriores (MRE). Essa foi uma das propostas feitas por representantes do governo acreano, [&#8230;] The post Governo do Acre busca pactuação para fortalecer integração física entre Brasil e Peru, com acesso por Cruzeiro do Sul appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/governo-do-acre-busca-pactuacao-para-fortalecer-integracao-fisica-entre-brasil-e-peru-com-acesso-por-cruzeiro-do-sul/",
    "sourceUrl": "https://agencia.ac.gov.br/governo-do-acre-busca-pactuacao-para-fortalecer-integracao-fisica-entre-brasil-e-peru-com-acesso-por-cruzeiro-do-sul/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Governo do Acre busca pactuação para fortalecer integração física entre Brasil e Peru, com acesso por Cruzeiro do Sul",
    "category": "Prefeitura",
    "publishedAt": "2026-04-17T21:59:47.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-16.39.07-3-1024x683.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-16.39.07-3-1024x683.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-16.39.07-1-1024x683.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/idaf-amplia-acoes-de-monitoramento-no-jurua-para-proteger-a-producao-de-banana-contra-a-praga-moko-da-bananeira/",
    "slug": "idaf-amplia-acoes-de-monitoramento-no-jurua-para-proteger-a-producao-de-banana-contra-a-praga-moko-da-bananeira",
    "title": "Idaf amplia ações de monitoramento no Juruá para proteger a produção de banana contra a praga moko da bananeira",
    "summary": "O registro do primeiro caso de moko da bananeira no município de Rodrigues Alves, na região do Juruá, acendeu um alerta no Acre e mobilizou o Instituto de Defesa Agropecuária e Florestal do Acre (Idaf) a intensificar as ações de monitoramento e erradicação da doença no estado. Ao longo desta semana, equipes formadas por engenheiros [&#8230;] The post Idaf amplia ações de monitoramento no Juruá para proteger a produção de banana contra a praga moko da bananeira appeared first on Noticias do Acre .",
    "lede": "O registro do primeiro caso de moko da bananeira no município de Rodrigues Alves, na região do Juruá, acendeu um alerta no Acre e mobilizou o Instituto de Defesa Agropecuária e Florestal do Acre (Idaf) a intensificar as ações de monitoramento e erradicação da doença no estado. Ao longo desta semana, equipes formadas por engenheiros [&#8230;] The post Idaf amplia ações de monitoramento no Juruá para proteger a produção de banana contra a praga moko da bananeira appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/idaf-amplia-acoes-de-monitoramento-no-jurua-para-proteger-a-producao-de-banana-contra-a-praga-moko-da-bananeira/",
    "sourceUrl": "https://agencia.ac.gov.br/idaf-amplia-acoes-de-monitoramento-no-jurua-para-proteger-a-producao-de-banana-contra-a-praga-moko-da-bananeira/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Idaf amplia ações de monitoramento no Juruá para proteger a produção de banana contra a praga moko da bananeira",
    "category": "Saúde",
    "publishedAt": "2026-04-17T21:52:11.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-15.28.16-654x1024.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-15.28.16-654x1024.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-16.39.07-1-1024x683.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/governos-do-acre-e-de-ucayali-realizam-1a-reuniao-do-comite-de-fronteira-centro-brasil-peru/",
    "slug": "governos-do-acre-e-de-ucayali-realizam-1-reuniao-do-comite-de-fronteira-centro-brasil-peru",
    "title": "Governos do Acre e de Ucayali realizam 1ª Reunião do Comitê de Fronteira Centro Brasil-Peru",
    "summary": "Representantes dos governos do Acre e Ucayali abriram na manhã desta sexta-feira, 17, a 1ª Reunião do Comitê de Fronteira Centro Brasil-Peru. O comitê é uma instância criada por meio de acordo publicado no Diário Oficial da União, em março deste ano e é voltada ao fortalecimento da cooperação bilateral entre o Brasil e o [&#8230;] The post Governos do Acre e de Ucayali realizam 1ª Reunião do Comitê de Fronteira Centro Brasil-Peru appeared first on Noticias do Acre .",
    "lede": "Representantes dos governos do Acre e Ucayali abriram na manhã desta sexta-feira, 17, a 1ª Reunião do Comitê de Fronteira Centro Brasil-Peru. O comitê é uma instância criada por meio de acordo publicado no Diário Oficial da União, em março deste ano e é voltada ao fortalecimento da cooperação bilateral entre o Brasil e o [&#8230;] The post Governos do Acre e de Ucayali realizam 1ª Reunião do Comitê de Fronteira Centro Brasil-Peru appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/governos-do-acre-e-de-ucayali-realizam-1a-reuniao-do-comite-de-fronteira-centro-brasil-peru/",
    "sourceUrl": "https://agencia.ac.gov.br/governos-do-acre-e-de-ucayali-realizam-1a-reuniao-do-comite-de-fronteira-centro-brasil-peru/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Governos do Acre e de Ucayali realizam 1ª Reunião do Comitê de Fronteira Centro Brasil-Peru",
    "category": "Negócios",
    "publishedAt": "2026-04-17T20:42:21.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-12.23.05-1024x683.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-12.23.05-1024x683.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-12.23.07-6-1024x683.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/acre-supera-media-nacional-e-registra-alta-de-143-no-abate-de-bovinos-com-mais-de-644-mil-cabecas/",
    "slug": "acre-supera-media-nacional-e-registra-alta-de-14-3-no-abate-de-bovinos-com-mais-de-644-mil-cabecas",
    "title": "Acre supera média nacional e registra alta de 14,3% no abate de bovinos, com mais de 644 mil cabeças",
    "summary": "O Acre registrou o abate de 644.196 bovinos em 2025, o que representa um crescimento de 14,3% em relação ao ano anterior, quando foram abatidas 563.599 cabeças. Os dados fazem parte da Pesquisa Trimestral do Abate de Animais, divulgada pelo Instituto Brasileiro de Geografia e Estatística (IBGE) no fim de março. As informações consideram apenas [&#8230;] The post Acre supera média nacional e registra alta de 14,3% no abate de bovinos, com mais de 644 mil cabeças appeared first on Noticias do Acre .",
    "lede": "O Acre registrou o abate de 644.196 bovinos em 2025, o que representa um crescimento de 14,3% em relação ao ano anterior, quando foram abatidas 563.599 cabeças. Os dados fazem parte da Pesquisa Trimestral do Abate de Animais, divulgada pelo Instituto Brasileiro de Geografia e Estatística (IBGE) no fim de março. As informações consideram apenas [&#8230;] The post Acre supera média nacional e registra alta de 14,3% no abate de bovinos, com mais de 644 mil cabeças appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/acre-supera-media-nacional-e-registra-alta-de-143-no-abate-de-bovinos-com-mais-de-644-mil-cabecas/",
    "sourceUrl": "https://agencia.ac.gov.br/acre-supera-media-nacional-e-registra-alta-de-143-no-abate-de-bovinos-com-mais-de-644-mil-cabecas/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Acre supera média nacional e registra alta de 14,3% no abate de bovinos, com mais de 644 mil cabeças",
    "category": "Prefeitura",
    "publishedAt": "2026-04-17T20:06:47.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-13.38.33-1024x680.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-13.38.33-1024x680.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/206877dc-b72b-48fa-9c85-27af9c67403d-1024x768.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/secretaria-de-administracao-compartilha-experiencias-na-2a-conferencia-nacional-de-arquivos/",
    "slug": "secretaria-de-administracao-compartilha-experiencias-na-2-conferencia-nacional-de-arquivos",
    "title": "Secretaria de Administração compartilha experiências na 2ª Conferência Nacional de Arquivos",
    "summary": "A Secretaria de Estado de Administração (Sead) participou da 2ª Conferência Nacional de Arquivos – Etapa Acre, realizada em Rio Branco, com o tema “Arquivos: agentes da cidadania e da democracia”. O encontro reuniu profissionais da área, gestores públicos e representantes da sociedade civil em um espaço de diálogo e construção de propostas voltadas ao [&#8230;] The post Secretaria de Administração compartilha experiências na 2ª Conferência Nacional de Arquivos appeared first on Noticias do Acre .",
    "lede": "A Secretaria de Estado de Administração (Sead) participou da 2ª Conferência Nacional de Arquivos – Etapa Acre, realizada em Rio Branco, com o tema “Arquivos: agentes da cidadania e da democracia”. O encontro reuniu profissionais da área, gestores públicos e representantes da sociedade civil em um espaço de diálogo e construção de propostas voltadas ao [&#8230;] The post Secretaria de Administração compartilha experiências na 2ª Conferência Nacional de Arquivos appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/secretaria-de-administracao-compartilha-experiencias-na-2a-conferencia-nacional-de-arquivos/",
    "sourceUrl": "https://agencia.ac.gov.br/secretaria-de-administracao-compartilha-experiencias-na-2a-conferencia-nacional-de-arquivos/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Secretaria de Administração compartilha experiências na 2ª Conferência Nacional de Arquivos",
    "category": "Prefeitura",
    "publishedAt": "2026-04-17T19:47:50.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/cd5bd2bd-a130-44e8-8c30-f7bcd25197ee-768x1024.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/cd5bd2bd-a130-44e8-8c30-f7bcd25197ee-768x1024.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/f0b85a1b-7fda-49be-a457-ecd236c93b82-1024x459.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/administracao-capacita-servidores-do-estado-para-fortalecer-a-gestao-do-patrimonio-publico/",
    "slug": "administracao-capacita-servidores-do-estado-para-fortalecer-a-gestao-do-patrimonio-publico",
    "title": "Administração capacita servidores do Estado para fortalecer a gestão do patrimônio público",
    "summary": "Por Aniely Cordeiro Com o objetivo de fortalecer a gestão patrimonial no Acre, a Secretaria de Estado de Administração (Sead) realizou nesta semana o treinamento Inventário de Bens Móveis e Intangíveis. A capacitação reuniu membros de comissões e chefes de setores patrimoniais de diversos órgãos estaduais. Estes profissionais atuam diretamente na execução, controle e validação [&#8230;] The post Administração capacita servidores do Estado para fortalecer a gestão do patrimônio público appeared first on Noticias do Acre .",
    "lede": "Por Aniely Cordeiro Com o objetivo de fortalecer a gestão patrimonial no Acre, a Secretaria de Estado de Administração (Sead) realizou nesta semana o treinamento Inventário de Bens Móveis e Intangíveis. A capacitação reuniu membros de comissões e chefes de setores patrimoniais de diversos órgãos estaduais. Estes profissionais atuam diretamente na execução, controle e validação [&#8230;] The post Administração capacita servidores do Estado para fortalecer a gestão do patrimônio público appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/administracao-capacita-servidores-do-estado-para-fortalecer-a-gestao-do-patrimonio-publico/",
    "sourceUrl": "https://agencia.ac.gov.br/administracao-capacita-servidores-do-estado-para-fortalecer-a-gestao-do-patrimonio-publico/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Administração capacita servidores do Estado para fortalecer a gestão do patrimônio público",
    "category": "Prefeitura",
    "publishedAt": "2026-04-17T19:43:43.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/4fdc1a9f-0d5b-4d94-9831-076b79ad71bd-1024x768.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/4fdc1a9f-0d5b-4d94-9831-076b79ad71bd-1024x768.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/f0b85a1b-7fda-49be-a457-ecd236c93b82-1024x459.jpeg"
  }
];
