window.NEWS_DATA = [
  {
    "id": "https://ac24horas.com/2026/04/17/partidas-da-2a-copa-acre-irao-decidir-mais-dois-semifinalistas/",
    "slug": "partidas-da-2-copa-acre-irao-decidir-mais-dois-semifinalistas",
    "title": "Partidas da 2ª Copa Acre irão decidir mais dois semifinalistas",
    "summary": "Foto Sueli Rodrigues: Semifinais da 2 Copa Acre serão disputadas no dia 24 \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-14-40-58-300x293.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-14-40-58-1200x1170.jpg\" A última rodada da fase de classificação da 2ª Copa Acre Sub-13 terá mais quatro partidas neste sábado, 18, no Tonicão, no CT do Cupuaçu e na Arena da Floresta. Jogos do grupo A O Santa Cruz, classificado para semifinal, enfrenta COPMBM, a partir das 8h30, no CT do Cupuaçu e joga para manter os [&#8230;]",
    "lede": "Foto Sueli Rodrigues: Semifinais da 2 Copa Acre serão disputadas no dia 24 \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-14-40-58-300x293.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-14-40-58-1200x1170.jpg\" A última rodada da fase de classificação da 2ª Copa Acre Sub-13 terá mais quatro partidas neste sábado, 18, no Tonicão, no CT do Cupuaçu e na Arena da Floresta. Jogos do grupo A O Santa Cruz, classificado para semifinal, enfrenta COPMBM, a partir das 8h30, no CT do Cupuaçu e joga para manter os [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/partidas-da-2a-copa-acre-irao-decidir-mais-dois-semifinalistas/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/partidas-da-2a-copa-acre-irao-decidir-mais-dois-semifinalistas/",
    "sourceName": "ac24horas",
    "sourceLabel": "Partidas da 2ª Copa Acre irão decidir mais dois semifinalistas",
    "category": "Esporte",
    "publishedAt": "2026-04-17T20:03:50.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-14-40-58-1200x1170.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-14-40-58-1200x1170.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-14-40-58-1200x1170.jpg"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/incra-amplia-para-122-familias-assentamento-entre-tarauaca-e-feijo/",
    "slug": "incra-amplia-para-122-familias-assentamento-entre-tarauaca-e-feijo",
    "title": "Incra amplia para 122 famílias assentamento entre Tarauacá e Feijó",
    "summary": "Foto: Jardy Lopes \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-09-as-11.54.54_97faa9e2-300x169.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-09-as-11.54.54_97faa9e2-1200x675.webp\" O Instituto Nacional de Colonização e Reforma Agrária (Incra) publicou nesta sexta-feira, 17, a Portaria nº 1.775, alterando a capacidade de atendimento do Projeto de Desenvolvimento Sustentável Acaraú, localizado nos municípios de Tarauacá e Feijó. O ato atualiza o número de famílias beneficiadas pelo assentamento criado no início deste ano. Com a mudança, a capacidade [&#8230;]",
    "lede": "Foto: Jardy Lopes \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-09-as-11.54.54_97faa9e2-300x169.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-09-as-11.54.54_97faa9e2-1200x675.webp\" O Instituto Nacional de Colonização e Reforma Agrária (Incra) publicou nesta sexta-feira, 17, a Portaria nº 1.775, alterando a capacidade de atendimento do Projeto de Desenvolvimento Sustentável Acaraú, localizado nos municípios de Tarauacá e Feijó. O ato atualiza o número de famílias beneficiadas pelo assentamento criado no início deste ano. Com a mudança, a capacidade [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/incra-amplia-para-122-familias-assentamento-entre-tarauaca-e-feijo/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/incra-amplia-para-122-familias-assentamento-entre-tarauaca-e-feijo/",
    "sourceName": "ac24horas",
    "sourceLabel": "Incra amplia para 122 famílias assentamento entre Tarauacá e Feijó",
    "category": "Saúde",
    "publishedAt": "2026-04-17T19:57:20.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-09-as-11.54.54_97faa9e2-1200x675.webp",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-09-as-11.54.54_97faa9e2-1200x675.webp",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2024/09/imagem-ilustrativa-abuso-estupro-agressao-violencia-contra-criancas-e-adolescentes-1600269547386_v2_1920x1280-1536x1024.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/chuvas-causam-transbordamento-de-igarape-e-interditam-trecho-da-br-364/",
    "slug": "chuvas-causam-transbordamento-de-igarape-e-interditam-trecho-da-br-364",
    "title": "Chuvas causam transbordamento de igarapé e interditam trecho da BR-364",
    "summary": "A rodovia BR-364 foi interditada parcialmente nesta sexta-feira (17), no trecho que liga Jaru a Ariquemes, em Rondônia. As fortes chuvas que atingiram a região nas últimas horas causaram o transbordamento de um igarapé que corta a rodovia federal. A força da água invadiu a pista e tornou a travessia extremamente perigosa, especialmente para veículos [&#8230;]",
    "lede": "A rodovia BR-364 foi interditada parcialmente nesta sexta-feira (17), no trecho que liga Jaru a Ariquemes, em Rondônia. As fortes chuvas que atingiram a região nas últimas horas causaram o transbordamento de um igarapé que corta a rodovia federal. A força da água invadiu a pista e tornou a travessia extremamente perigosa, especialmente para veículos [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/chuvas-causam-transbordamento-de-igarape-e-interditam-trecho-da-br-364/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/chuvas-causam-transbordamento-de-igarape-e-interditam-trecho-da-br-364/",
    "sourceName": "ac24horas",
    "sourceLabel": "Chuvas causam transbordamento de igarapé e interditam trecho da BR-364",
    "category": "Utilidade Pública",
    "publishedAt": "2026-04-17T19:43:15.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-13-54-06.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-17-13-54-06.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2024/09/imagem-ilustrativa-abuso-estupro-agressao-violencia-contra-criancas-e-adolescentes-1600269547386_v2_1920x1280-1536x1024.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/crianca-indigena-de-4-anos-cai-de-canoa-e-desaparece-no-rio-purus/",
    "slug": "crianca-indigena-de-4-anos-cai-de-canoa-e-desaparece-no-rio-purus",
    "title": "Criança indígena de 4 anos cai de canoa e desaparece no Rio Purus",
    "summary": "Foto: Mizael Louzada \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-10-as-10.47.18_01ba5c88-300x169.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-10-as-10.47.18_01ba5c88-1200x675.webp\" Uma criança indígena de 4 anos caiu de uma canoa e desapareceu no rio Purus na quinta-feira (16), em área próxima ao município de Santa Rosa do Purus, no interior do Acre. A vítima viajava com os pais no momento do acidente. De acordo com as primeiras informações, a embarcação foi atingida por um objeto [&#8230;]",
    "lede": "Foto: Mizael Louzada \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-10-as-10.47.18_01ba5c88-300x169.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-10-as-10.47.18_01ba5c88-1200x675.webp\" Uma criança indígena de 4 anos caiu de uma canoa e desapareceu no rio Purus na quinta-feira (16), em área próxima ao município de Santa Rosa do Purus, no interior do Acre. A vítima viajava com os pais no momento do acidente. De acordo com as primeiras informações, a embarcação foi atingida por um objeto [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/crianca-indigena-de-4-anos-cai-de-canoa-e-desaparece-no-rio-purus/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/crianca-indigena-de-4-anos-cai-de-canoa-e-desaparece-no-rio-purus/",
    "sourceName": "ac24horas",
    "sourceLabel": "Criança indígena de 4 anos cai de canoa e desaparece no Rio Purus",
    "category": "Negócios",
    "publishedAt": "2026-04-17T19:42:03.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-10-as-10.47.18_01ba5c88-1200x675.webp",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2025/04/Imagem-do-WhatsApp-de-2025-04-10-as-10.47.18_01ba5c88-1200x675.webp",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2024/09/imagem-ilustrativa-abuso-estupro-agressao-violencia-contra-criancas-e-adolescentes-1600269547386_v2_1920x1280-1536x1024.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/sextou-em-manaus-gladson-aparece-dirigindo-fala-sobre-planos-nas-eleicoes-e-retorno-ao-acre/",
    "slug": "8220-sextou-em-manaus-gladson-aparece-dirigindo-fala-sobre-planos-nas-eleicoes-e-retorno-ao-acre",
    "title": "&#8220;Sextou em Manaus”: Gladson aparece dirigindo, fala sobre planos nas eleições e retorno ao Acre",
    "summary": "Foto: Instagram \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/GLADSON_EXTOU--300x169.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/GLADSON_EXTOU-.jpg\" O ex-governador do Acre Gladson Cameli publicou um vídeo nas redes sociais nesta sexta-feira (17) em que aparece dirigindo e fala sobre sua saída do cargo de governador e sobre a visita que faz a Manaus, onde está com a família e reuniu-se com o grupo empresarial da família. No vídeo, Cameli reafirmou que abriu [&#8230;]",
    "lede": "Foto: Instagram \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/GLADSON_EXTOU--300x169.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/GLADSON_EXTOU-.jpg\" O ex-governador do Acre Gladson Cameli publicou um vídeo nas redes sociais nesta sexta-feira (17) em que aparece dirigindo e fala sobre sua saída do cargo de governador e sobre a visita que faz a Manaus, onde está com a família e reuniu-se com o grupo empresarial da família. No vídeo, Cameli reafirmou que abriu [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/sextou-em-manaus-gladson-aparece-dirigindo-fala-sobre-planos-nas-eleicoes-e-retorno-ao-acre/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/sextou-em-manaus-gladson-aparece-dirigindo-fala-sobre-planos-nas-eleicoes-e-retorno-ao-acre/",
    "sourceName": "ac24horas",
    "sourceLabel": "&#8220;Sextou em Manaus”: Gladson aparece dirigindo, fala sobre planos nas eleições e retorno ao Acre",
    "category": "Prefeitura",
    "publishedAt": "2026-04-17T19:35:03.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/GLADSON_EXTOU-.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/GLADSON_EXTOU-.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-15-at-09.47.50-2-1200x801.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/puyanawas-terao-mais-de-400-litros-de-caicuma-na-festa-dos-povos-indigenas-em-mancio-lima/",
    "slug": "puyanawas-terao-mais-de-400-litros-de-caicuma-na-festa-dos-povos-indigenas-em-mancio-lima",
    "title": "Puyanawas terão mais de 400 litros de caiçuma na festa dos Povos Indígenas em Mâncio Lima",
    "summary": "Foto: Iverson Ibernon \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/IMG_3861-1-300x202.jpeg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/IMG_3861-1.jpeg\" Mais de 400 litros de caiçuma estarão a disposição para o consumo do público que for celebrar domingo, 19, o Dia dos Povos Indígenas, na Terra Indígena Puyanawa, em Mâncio Lima. O evento será realizado no Centro Cultural da Aldeia Barão das 08h30 às 17h. A entrada será gratuita e a programação terá fala das [&#8230;]",
    "lede": "Foto: Iverson Ibernon \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/IMG_3861-1-300x202.jpeg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/IMG_3861-1.jpeg\" Mais de 400 litros de caiçuma estarão a disposição para o consumo do público que for celebrar domingo, 19, o Dia dos Povos Indígenas, na Terra Indígena Puyanawa, em Mâncio Lima. O evento será realizado no Centro Cultural da Aldeia Barão das 08h30 às 17h. A entrada será gratuita e a programação terá fala das [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/puyanawas-terao-mais-de-400-litros-de-caicuma-na-festa-dos-povos-indigenas-em-mancio-lima/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/puyanawas-terao-mais-de-400-litros-de-caicuma-na-festa-dos-povos-indigenas-em-mancio-lima/",
    "sourceName": "ac24horas",
    "sourceLabel": "Puyanawas terão mais de 400 litros de caiçuma na festa dos Povos Indígenas em Mâncio Lima",
    "category": "Festas & Social",
    "publishedAt": "2026-04-17T19:28:23.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_3861-1.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_3861-1.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/52edcf0a-6a87-4539-b221-dbb2005e726d-815x1200.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/calor-chuvas-intensas-e-alerta-para-subida-rapida-do-rio-acre-marcam-o-feriadao/",
    "slug": "calor-chuvas-intensas-e-alerta-para-subida-rapida-do-rio-acre-marcam-o-feriadao",
    "title": "Calor, chuvas intensas e alerta para subida rápida do Rio Acre marcam o feriadão",
    "summary": "Foto: Jardy Lopes \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2025/06/Imagem-do-WhatsApp-de-2025-06-24-as-18.00.14_c738d3ea-300x169.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2025/06/Imagem-do-WhatsApp-de-2025-06-24-as-18.00.14_c738d3ea-1200x675.webp\" O Acre deve enfrentar um feriadão com tempo quente e abafado, além de chuvas diárias que podem ser fortes em várias regiões. A previsão é do portal O Tempo Aqui, que também emitiu alerta para rápida e acentuada elevação do nível do Rio Acre, principalmente em Rio Branco (AC). Os dados foram divulgados nesta sexta-feira [&#8230;]",
    "lede": "Foto: Jardy Lopes \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2025/06/Imagem-do-WhatsApp-de-2025-06-24-as-18.00.14_c738d3ea-300x169.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2025/06/Imagem-do-WhatsApp-de-2025-06-24-as-18.00.14_c738d3ea-1200x675.webp\" O Acre deve enfrentar um feriadão com tempo quente e abafado, além de chuvas diárias que podem ser fortes em várias regiões. A previsão é do portal O Tempo Aqui, que também emitiu alerta para rápida e acentuada elevação do nível do Rio Acre, principalmente em Rio Branco (AC). Os dados foram divulgados nesta sexta-feira [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/calor-chuvas-intensas-e-alerta-para-subida-rapida-do-rio-acre-marcam-o-feriadao/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/calor-chuvas-intensas-e-alerta-para-subida-rapida-do-rio-acre-marcam-o-feriadao/",
    "sourceName": "ac24horas",
    "sourceLabel": "Calor, chuvas intensas e alerta para subida rápida do Rio Acre marcam o feriadão",
    "category": "Cotidiano",
    "publishedAt": "2026-04-17T19:24:17.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2025/06/Imagem-do-WhatsApp-de-2025-06-24-as-18.00.14_c738d3ea-1200x675.webp",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2025/06/Imagem-do-WhatsApp-de-2025-06-24-as-18.00.14_c738d3ea-1200x675.webp",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/31012969-c3b4-4c10-a60c-20f7121181c6-2048x1420-1.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/mais-de-49-mil-acreanos-ja-enviaram-declaracao-do-ir-2026-aponta-levantamento/",
    "slug": "mais-de-49-mil-acreanos-ja-enviaram-declaracao-do-ir-2026",
    "title": "Mais de 49 mil acreanos já enviaram declaração do IR 2026",
    "summary": "O Acre já contabiliza 49.021 declarações do Imposto de Renda Pessoa Física 2026 enviadas até às 15h11 desta sexta-feira (17). Os dados mostram que a maior parte dos contribuintes do estado tem valores a receber: 80,1% das declarações indicam restituição, enquanto 12,8% terão imposto a pagar e 7,1% não apresentaram imposto devido. Entre os envios, [&#8230;]",
    "lede": "O Acre já contabiliza 49.021 declarações do Imposto de Renda Pessoa Física 2026 enviadas até às 15h11 desta sexta-feira (17). Os dados mostram que a maior parte dos contribuintes do estado tem valores a receber: 80,1% das declarações indicam restituição, enquanto 12,8% terão imposto a pagar e 7,1% não apresentaram imposto devido. Entre os envios, [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/mais-de-49-mil-acreanos-ja-enviaram-declaracao-do-ir-2026-aponta-levantamento/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/mais-de-49-mil-acreanos-ja-enviaram-declaracao-do-ir-2026-aponta-levantamento/",
    "sourceName": "ac24horas",
    "sourceLabel": "Mais de 49 mil acreanos já enviaram declaração do IR 2026",
    "category": "Negócios",
    "publishedAt": "2026-04-17T19:22:00.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/114264943-riodejaneirorj16-03-2026-economia-imagensilustrativadoaplicativodareceitafed.avif",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/114264943-riodejaneirorj16-03-2026-economia-imagensilustrativadoaplicativodareceitafed.avif",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2024/09/imagem-ilustrativa-abuso-estupro-agressao-violencia-contra-criancas-e-adolescentes-1600269547386_v2_1920x1280-1536x1024.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/boletim-infogripe-coloca-acre-em-nivel-de-alerta-por-aumento-de-internacoes-respiratorias/",
    "slug": "boletim-infogripe-coloca-acre-em-nivel-de-alerta-por-aumento-de-internacoes-respiratorias",
    "title": "Boletim InfoGripe coloca Acre em nível de alerta por aumento de internações respiratórias",
    "summary": "(Foto: Freepik) \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/02/976x695_IMAGEM-DESTACADA-19-300x214.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/02/976x695_IMAGEM-DESTACADA-19.webp\" O novo boletim do Fiocruz acendeu um alerta para o Acre após identificar aumento de casos de Síndrome Respiratória Aguda Grave (SRAG), especialmente entre crianças pequenas. Os dados da estratégia InfoGripe, referentes à Semana Epidemiológica 14 (de 5 a 11 de abril), mostram que o estado está entre as unidades da federação com incidência em [&#8230;]",
    "lede": "(Foto: Freepik) \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/02/976x695_IMAGEM-DESTACADA-19-300x214.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/02/976x695_IMAGEM-DESTACADA-19.webp\" O novo boletim do Fiocruz acendeu um alerta para o Acre após identificar aumento de casos de Síndrome Respiratória Aguda Grave (SRAG), especialmente entre crianças pequenas. Os dados da estratégia InfoGripe, referentes à Semana Epidemiológica 14 (de 5 a 11 de abril), mostram que o estado está entre as unidades da federação com incidência em [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/boletim-infogripe-coloca-acre-em-nivel-de-alerta-por-aumento-de-internacoes-respiratorias/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/boletim-infogripe-coloca-acre-em-nivel-de-alerta-por-aumento-de-internacoes-respiratorias/",
    "sourceName": "ac24horas",
    "sourceLabel": "Boletim InfoGripe coloca Acre em nível de alerta por aumento de internações respiratórias",
    "category": "Utilidade Pública",
    "publishedAt": "2026-04-17T19:20:02.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/02/976x695_IMAGEM-DESTACADA-19.webp",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/02/976x695_IMAGEM-DESTACADA-19.webp",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/03/carne_dest--1200x900.jpg"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/uraps-funcionam-em-horario-reduzido-no-feriado-de-tiradentes/",
    "slug": "uraps-funcionam-em-horario-reduzido-no-feriado-de-tiradentes",
    "title": "URAPs funcionam em horário reduzido no feriado de Tiradentes",
    "summary": "FOTO: DAVID MEDEIROS \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2025/02/Urap-12-1-e1708813260866-300x169.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2025/02/Urap-12-1-e1708813260866-900x507.jpg\" A Secretaria Municipal de Saúde de Rio Branco divulgou, nesta sexta-feira (17), que as quatro Unidades de Referência de Atenção Primária (URAPs) vão funcionar em horário reduzido durante o ponto facultativo de segunda-feira (20) e o feriado nacional de Tiradentes, na terça-feira (21). O atendimento nas unidades ocorre das 7h às 13h nos dois dias. [&#8230;]",
    "lede": "FOTO: DAVID MEDEIROS \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2025/02/Urap-12-1-e1708813260866-300x169.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2025/02/Urap-12-1-e1708813260866-900x507.jpg\" A Secretaria Municipal de Saúde de Rio Branco divulgou, nesta sexta-feira (17), que as quatro Unidades de Referência de Atenção Primária (URAPs) vão funcionar em horário reduzido durante o ponto facultativo de segunda-feira (20) e o feriado nacional de Tiradentes, na terça-feira (21). O atendimento nas unidades ocorre das 7h às 13h nos dois dias. [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/uraps-funcionam-em-horario-reduzido-no-feriado-de-tiradentes/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/uraps-funcionam-em-horario-reduzido-no-feriado-de-tiradentes/",
    "sourceName": "ac24horas",
    "sourceLabel": "URAPs funcionam em horário reduzido no feriado de Tiradentes",
    "category": "Saúde",
    "publishedAt": "2026-04-17T18:15:20.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2025/02/Urap-12-1-e1708813260866.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2025/02/Urap-12-1-e1708813260866.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/03/FOTO-SEE-2025.1-1536x1023-1.jpg"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/nova-instrucao-do-tce-ac-flexibiliza-idade-para-auxilio-creche-em-casos-de-deficiencia/",
    "slug": "nova-instrucao-do-tce-ac-flexibiliza-idade-para-auxilio-creche-em-casos-de-deficiencia",
    "title": "Nova instrução do TCE-AC flexibiliza idade para auxílio-creche em casos de deficiência",
    "summary": "Foto: Sérgio Vale \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2024/12/TCE-1-300x196.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2024/12/TCE-1-900x587.jpg\" O Tribunal de Contas do Estado do Acre publicou nesta sexta-feira, 17, a Instrução Normativa nº 46, de 19 de março de 2026, que altera dispositivos da norma anterior que regulamenta a concessão do auxílio-creche no âmbito da Corte. As mudanças atualizam a Instrução Normativa nº 31/2024 e incorporam ajustes previstos na Lei nº 4.744, [&#8230;]",
    "lede": "Foto: Sérgio Vale \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2024/12/TCE-1-300x196.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2024/12/TCE-1-900x587.jpg\" O Tribunal de Contas do Estado do Acre publicou nesta sexta-feira, 17, a Instrução Normativa nº 46, de 19 de março de 2026, que altera dispositivos da norma anterior que regulamenta a concessão do auxílio-creche no âmbito da Corte. As mudanças atualizam a Instrução Normativa nº 31/2024 e incorporam ajustes previstos na Lei nº 4.744, [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/nova-instrucao-do-tce-ac-flexibiliza-idade-para-auxilio-creche-em-casos-de-deficiencia/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/nova-instrucao-do-tce-ac-flexibiliza-idade-para-auxilio-creche-em-casos-de-deficiencia/",
    "sourceName": "ac24horas",
    "sourceLabel": "Nova instrução do TCE-AC flexibiliza idade para auxílio-creche em casos de deficiência",
    "category": "Política",
    "publishedAt": "2026-04-17T18:13:41.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2024/12/TCE-1-1536x1002.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2024/12/TCE-1-1536x1002.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-16-15-37-26-1200x801.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/profissional-acusada-de-causar-queimaduras-em-acreana-nega-irregularidades-cliente-nao-seguiu-o-pos/",
    "slug": "profissional-acusada-de-causar-queimaduras-em-acreana-nega-irregularidades-nao-seguiu-o-pos",
    "title": "Profissional acusada de causar queimaduras em acreana nega irregularidades: “não seguiu o pós”",
    "summary": "Em entrevista exclusiva ao ac24horas nesta sexta-feira (17), a profissional identificada pelas iniciais N.A., acusada de causar queimaduras graves no seio de uma cliente durante procedimento estético em Cruzeiro do Sul, negou as acusações e afirmou que o atendimento foi realizado dentro dos parâmetros técnicos e científicos exigidos para a técnica utilizada. N.A. afirma não [&#8230;]",
    "lede": "Em entrevista exclusiva ao ac24horas nesta sexta-feira (17), a profissional identificada pelas iniciais N.A., acusada de causar queimaduras graves no seio de uma cliente durante procedimento estético em Cruzeiro do Sul, negou as acusações e afirmou que o atendimento foi realizado dentro dos parâmetros técnicos e científicos exigidos para a técnica utilizada. N.A. afirma não [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/profissional-acusada-de-causar-queimaduras-em-acreana-nega-irregularidades-cliente-nao-seguiu-o-pos/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/profissional-acusada-de-causar-queimaduras-em-acreana-nega-irregularidades-cliente-nao-seguiu-o-pos/",
    "sourceName": "ac24horas",
    "sourceLabel": "Profissional acusada de causar queimaduras em acreana nega irregularidades: “não seguiu o pós”",
    "category": "Saúde",
    "publishedAt": "2026-04-17T18:12:09.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-12.45.20-1-675x1200.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-12.45.20-1-675x1200.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-12.45.20-1-675x1200.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/zequinha-lima-e-eleito-presidente-da-amac-objetivo-e-ajudar-os-municipios-a-avancarem/",
    "slug": "zequinha-lima-e-eleito-presidente-da-amac-objetivo-e-ajudar-os-municipios-a-avancarem",
    "title": "Zequinha Lima é eleito presidente da AMAC: “objetivo é ajudar os municípios a avançarem”",
    "summary": "O prefeito de Cruzeiro do Sul, Zequinha Lima, é o novo presidente da Associação dos Municípios do Acre (AMAC). O prefeito de Rio Branco, Alysson Bestene é o vice e o 1º secretário é Jerry Correia, gestor de Assis Brasil. A escolha ocorreu durante assembleia realizada na sede da entidade, em Rio Branco nesta sexta-feira, [&#8230;]",
    "lede": "O prefeito de Cruzeiro do Sul, Zequinha Lima, é o novo presidente da Associação dos Municípios do Acre (AMAC). O prefeito de Rio Branco, Alysson Bestene é o vice e o 1º secretário é Jerry Correia, gestor de Assis Brasil. A escolha ocorreu durante assembleia realizada na sede da entidade, em Rio Branco nesta sexta-feira, [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/zequinha-lima-e-eleito-presidente-da-amac-objetivo-e-ajudar-os-municipios-a-avancarem/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/zequinha-lima-e-eleito-presidente-da-amac-objetivo-e-ajudar-os-municipios-a-avancarem/",
    "sourceName": "ac24horas",
    "sourceLabel": "Zequinha Lima é eleito presidente da AMAC: “objetivo é ajudar os municípios a avançarem”",
    "category": "Prefeitura",
    "publishedAt": "2026-04-17T18:08:29.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/92a6e732-4782-4dd0-a2fc-ccd7453ad29d.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/92a6e732-4782-4dd0-a2fc-ccd7453ad29d.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG-20250803-WA0038-1200x831-1.webp"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/railson-ferreira-anuncia-construcao-de-50-casas-na-zona-rural-de-feijo/",
    "slug": "railson-ferreira-anuncia-construcao-de-50-casas-na-zona-rural-de-feijo",
    "title": "Railson Ferreira anuncia construção de 50 casas na zona rural de Feijó",
    "summary": "O prefeito de Feijó, Railson Ferreira, em um anúncio conjunto com o Deputado Federal Roberto Duarte e o vice-prefeito Juarez Leitão, revelou um projeto ambicioso: a construção de 50 casas destinadas à zona rural do município. Essa iniciativa surge em um momento em que a demanda por moradia adequada se torna cada vez mais evidente, [&#8230;]",
    "lede": "O prefeito de Feijó, Railson Ferreira, em um anúncio conjunto com o Deputado Federal Roberto Duarte e o vice-prefeito Juarez Leitão, revelou um projeto ambicioso: a construção de 50 casas destinadas à zona rural do município. Essa iniciativa surge em um momento em que a demanda por moradia adequada se torna cada vez mais evidente, [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/railson-ferreira-anuncia-construcao-de-50-casas-na-zona-rural-de-feijo/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/railson-ferreira-anuncia-construcao-de-50-casas-na-zona-rural-de-feijo/",
    "sourceName": "ac24horas",
    "sourceLabel": "Railson Ferreira anuncia construção de 50 casas na zona rural de Feijó",
    "category": "Prefeitura",
    "publishedAt": "2026-04-17T17:34:02.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/CASA_FEIJO-.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/CASA_FEIJO-.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/03/FOTO-SEE-2025.1-1536x1023-1.jpg"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/ajustes-sao-necessarios-para-que-erros-de-secretarios-nao-caiam-na-conta-de-mailza/",
    "slug": "ajustes-sao-necessarios-para-que-erros-de-secretarios-nao-caiam-na-conta-de-mailza",
    "title": "Ajustes são necessários para que erros de secretários não caiam na conta de Mailza",
    "summary": "Foto: Iago Nascimento \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-20-at-11.53.32-300x200.jpeg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-20-at-11.53.32-1200x800.jpeg\" O cenário político acreano desta semana foi movimentado por articulações para a sucessão estadual, disputas internas em grupos políticos e novas polêmicas envolvendo nomeações no governo. Nos bastidores, os analistas políticos Astério Moreira e Crica, ao lado do apresentador Marcos Venícios, avaliaram alianças das eleições de 2026, enquanto declarações públicas acirraram o clima entre aliados [&#8230;]",
    "lede": "Foto: Iago Nascimento \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-20-at-11.53.32-300x200.jpeg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-20-at-11.53.32-1200x800.jpeg\" O cenário político acreano desta semana foi movimentado por articulações para a sucessão estadual, disputas internas em grupos políticos e novas polêmicas envolvendo nomeações no governo. Nos bastidores, os analistas políticos Astério Moreira e Crica, ao lado do apresentador Marcos Venícios, avaliaram alianças das eleições de 2026, enquanto declarações públicas acirraram o clima entre aliados [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/ajustes-sao-necessarios-para-que-erros-de-secretarios-nao-caiam-na-conta-de-mailza/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/ajustes-sao-necessarios-para-que-erros-de-secretarios-nao-caiam-na-conta-de-mailza/",
    "sourceName": "ac24horas",
    "sourceLabel": "Ajustes são necessários para que erros de secretários não caiam na conta de Mailza",
    "category": "Prefeitura",
    "publishedAt": "2026-04-17T17:23:04.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-20-at-11.53.32-1200x800.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-20-at-11.53.32-1200x800.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/31012969-c3b4-4c10-a60c-20f7121181c6-2048x1420-1.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/estado-convida-empreendedores-de-ucayali-para-expor-produtos-na-expoacre-2026/",
    "slug": "estado-convida-empreendedores-de-ucayali-para-expor-produtos-na-expoacre-2026",
    "title": "Estado convida empreendedores de Ucayali para expor produtos na Expoacre 2026",
    "summary": "Representantes do governo do Acre desembarcaram na tarde desta quinta-feira, 16, em Pucallpa, capital do Departamento de Ucayali, onde foram recebidos pelo governador Manuel Gambini no Cite Florestal, um centro de inovação e tecnologia que apoia empreendedores locais de diversas áreas da bioeconomia. Governador de Ucayali, Manuel Gambini, recebeu a comitiva acreana no Cite Florestal, [&#8230;]",
    "lede": "Representantes do governo do Acre desembarcaram na tarde desta quinta-feira, 16, em Pucallpa, capital do Departamento de Ucayali, onde foram recebidos pelo governador Manuel Gambini no Cite Florestal, um centro de inovação e tecnologia que apoia empreendedores locais de diversas áreas da bioeconomia. Governador de Ucayali, Manuel Gambini, recebeu a comitiva acreana no Cite Florestal, [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/estado-convida-empreendedores-de-ucayali-para-expor-produtos-na-expoacre-2026/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/estado-convida-empreendedores-de-ucayali-para-expor-produtos-na-expoacre-2026/",
    "sourceName": "ac24horas",
    "sourceLabel": "Estado convida empreendedores de Ucayali para expor produtos na Expoacre 2026",
    "category": "Cotidiano",
    "publishedAt": "2026-04-17T17:17:28.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/31012969-c3b4-4c10-a60c-20f7121181c6-2048x1420-1.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/31012969-c3b4-4c10-a60c-20f7121181c6-2048x1420-1.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/31012969-c3b4-4c10-a60c-20f7121181c6-2048x1420-1.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/esquema-milionario-lider-de-quadrilha-de-fraudes-digitais-e-capturado-no-acre/",
    "slug": "esquema-milionario-lider-de-quadrilha-de-fraudes-digitais-e-capturado-no-acre",
    "title": "Esquema milionário: líder de quadrilha de fraudes digitais é capturado no Acre",
    "summary": "A Polícia Civil do Acre prendeu, nesta sexta-feira (17), um dos líderes de uma organização criminosa voltada para a prática de fraudes eletrônicas. A prisão foi resultado de um longo trabalho de monitoramento conduzido pelo Departamento de Polícia da Capital e Interior (DPCI). O investigado havia escapado da Justiça por cerca de um ano antes [&#8230;]",
    "lede": "A Polícia Civil do Acre prendeu, nesta sexta-feira (17), um dos líderes de uma organização criminosa voltada para a prática de fraudes eletrônicas. A prisão foi resultado de um longo trabalho de monitoramento conduzido pelo Departamento de Polícia da Capital e Interior (DPCI). O investigado havia escapado da Justiça por cerca de um ano antes [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/esquema-milionario-lider-de-quadrilha-de-fraudes-digitais-e-capturado-no-acre/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/esquema-milionario-lider-de-quadrilha-de-fraudes-digitais-e-capturado-no-acre/",
    "sourceName": "ac24horas",
    "sourceLabel": "Esquema milionário: líder de quadrilha de fraudes digitais é capturado no Acre",
    "category": "Polícia",
    "publishedAt": "2026-04-17T17:13:24.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_7184.png",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_7184.png",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/31012969-c3b4-4c10-a60c-20f7121181c6-2048x1420-1.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/memorial-antonio-aquino-e-inaugurado-com-a-presenca-de-familiares-dirigentes-e-ex-atletas/",
    "slug": "memorial-antonio-aquino-e-inaugurado-com-a-presenca-de-familiares-dirigentes-e-ex-atletas",
    "title": "Memorial Antônio Aquino é inaugurado com a presença de familiares, dirigentes e ex-atletas",
    "summary": "Fotos Sueli Rodrigues: Memorial Antônio Aquino registra parte da história do futebol acreano \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-11.51.31-300x200.jpeg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-11.51.31-1200x801.jpeg\" O Memorial Antônio Aquino foi inaugurado nesta sexta, 17, na Federação de Futebol do Acre(FFAC) com a presença de familiares, dirigentes e ex-atletas. O saudoso Antônio Aquino morreu em 16 de abril de 2025 e comandou a entidade por 41 anos. “Esse memorial conta parte da história do futebol acreano. A construção da atual estrutura [&#8230;]",
    "lede": "Fotos Sueli Rodrigues: Memorial Antônio Aquino registra parte da história do futebol acreano \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-11.51.31-300x200.jpeg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-11.51.31-1200x801.jpeg\" O Memorial Antônio Aquino foi inaugurado nesta sexta, 17, na Federação de Futebol do Acre(FFAC) com a presença de familiares, dirigentes e ex-atletas. O saudoso Antônio Aquino morreu em 16 de abril de 2025 e comandou a entidade por 41 anos. “Esse memorial conta parte da história do futebol acreano. A construção da atual estrutura [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/memorial-antonio-aquino-e-inaugurado-com-a-presenca-de-familiares-dirigentes-e-ex-atletas/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/memorial-antonio-aquino-e-inaugurado-com-a-presenca-de-familiares-dirigentes-e-ex-atletas/",
    "sourceName": "ac24horas",
    "sourceLabel": "Memorial Antônio Aquino é inaugurado com a presença de familiares, dirigentes e ex-atletas",
    "category": "Esporte",
    "publishedAt": "2026-04-17T17:12:07.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-11.51.31-1200x801.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-11.51.31-1200x801.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/31012969-c3b4-4c10-a60c-20f7121181c6-2048x1420-1.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/comediante-tecnica-de-enfermagem-traz-show-de-stand-up-a-rio-branco/",
    "slug": "comediante-tecnica-de-enfermagem-traz-show-de-stand-up-a-rio-branco",
    "title": "Comediante técnica de enfermagem traz show de stand-up a Rio Branco",
    "summary": "A comediante Camila Cardoso, técnica de enfermagem e humorista com 1,6 milhão de seguidores no Instagram, traz o espetáculo “Antes e Depois do Plantão” a Rio Branco na terça-feira (1º) de julho. A apresentação acontece no Auditório da Livraria Paim, a partir das 20h. O show tem como personagem central uma técnica de enfermagem e [&#8230;]",
    "lede": "A comediante Camila Cardoso, técnica de enfermagem e humorista com 1,6 milhão de seguidores no Instagram, traz o espetáculo “Antes e Depois do Plantão” a Rio Branco na terça-feira (1º) de julho. A apresentação acontece no Auditório da Livraria Paim, a partir das 20h. O show tem como personagem central uma técnica de enfermagem e [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/comediante-tecnica-de-enfermagem-traz-show-de-stand-up-a-rio-branco/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/comediante-tecnica-de-enfermagem-traz-show-de-stand-up-a-rio-branco/",
    "sourceName": "ac24horas",
    "sourceLabel": "Comediante técnica de enfermagem traz show de stand-up a Rio Branco",
    "category": "Negócios",
    "publishedAt": "2026-04-17T16:43:36.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/CAMILA_ALN.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/CAMILA_ALN.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2025-05-01-at-02.01.35-4-1200x800.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/17/jovem-de-18-anos-com-tres-mandados-de-prisao-e-detido-em-mancio-lima/",
    "slug": "jovem-de-18-anos-com-tres-mandados-de-prisao-e-detido-em-mancio-lima",
    "title": "Jovem de 18 anos com três mandados de prisão é detido em Mâncio Lima",
    "summary": "Um jovem de, de 18 anos,Jonathan,foi preso pelo Grupo Especial de Fronteira (Fefron) e Polícia Civil nesta sexta-feira,17, em Mâncio Lima. Contra ele havia três mandados de prisão em aberto. Ele é apontado como autor de roubos, bem como membro de organização criminosa na região, com atuação predominante no município de Mâncio Lima. Ele foi [&#8230;]",
    "lede": "Um jovem de, de 18 anos,Jonathan,foi preso pelo Grupo Especial de Fronteira (Fefron) e Polícia Civil nesta sexta-feira,17, em Mâncio Lima. Contra ele havia três mandados de prisão em aberto. Ele é apontado como autor de roubos, bem como membro de organização criminosa na região, com atuação predominante no município de Mâncio Lima. Ele foi [&#8230;]",
    "url": "https://ac24horas.com/2026/04/17/jovem-de-18-anos-com-tres-mandados-de-prisao-e-detido-em-mancio-lima/",
    "sourceUrl": "https://ac24horas.com/2026/04/17/jovem-de-18-anos-com-tres-mandados-de-prisao-e-detido-em-mancio-lima/",
    "sourceName": "ac24horas",
    "sourceLabel": "Jovem de 18 anos com três mandados de prisão é detido em Mâncio Lima",
    "category": "Polícia",
    "publishedAt": "2026-04-17T16:36:17.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/52edcf0a-6a87-4539-b221-dbb2005e726d-815x1200.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/52edcf0a-6a87-4539-b221-dbb2005e726d-815x1200.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/52edcf0a-6a87-4539-b221-dbb2005e726d-815x1200.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/secretaria-de-administracao-compartilha-experiencias-na-2a-conferencia-nacional-de-arquivos/",
    "slug": "secretaria-de-administracao-compartilha-experiencias-na-2-conferencia-nacional-de-arquivos",
    "title": "Secretaria de Administração compartilha experiências na 2ª Conferência Nacional de Arquivos",
    "summary": "A Secretaria de Estado de Administração (Sead) participou da 2ª Conferência Nacional de Arquivos – Etapa Acre, realizada em Rio Branco, com o tema “Arquivos: agentes da cidadania e da democracia”. O encontro reuniu profissionais da área, gestores públicos e representantes da sociedade civil em um espaço de diálogo e construção de propostas voltadas ao [&#8230;] The post Secretaria de Administração compartilha experiências na 2ª Conferência Nacional de Arquivos appeared first on Noticias do Acre .",
    "lede": "A Secretaria de Estado de Administração (Sead) participou da 2ª Conferência Nacional de Arquivos – Etapa Acre, realizada em Rio Branco, com o tema “Arquivos: agentes da cidadania e da democracia”. O encontro reuniu profissionais da área, gestores públicos e representantes da sociedade civil em um espaço de diálogo e construção de propostas voltadas ao [&#8230;] The post Secretaria de Administração compartilha experiências na 2ª Conferência Nacional de Arquivos appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/secretaria-de-administracao-compartilha-experiencias-na-2a-conferencia-nacional-de-arquivos/",
    "sourceUrl": "https://agencia.ac.gov.br/secretaria-de-administracao-compartilha-experiencias-na-2a-conferencia-nacional-de-arquivos/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Secretaria de Administração compartilha experiências na 2ª Conferência Nacional de Arquivos",
    "category": "Prefeitura",
    "publishedAt": "2026-04-17T19:47:50.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/cd5bd2bd-a130-44e8-8c30-f7bcd25197ee-768x1024.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/cd5bd2bd-a130-44e8-8c30-f7bcd25197ee-768x1024.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/f0b85a1b-7fda-49be-a457-ecd236c93b82-1024x459.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/administracao-capacita-servidores-do-estado-para-fortalecer-a-gestao-do-patrimonio-publico/",
    "slug": "administracao-capacita-servidores-do-estado-para-fortalecer-a-gestao-do-patrimonio-publico",
    "title": "Administração capacita servidores do Estado para fortalecer a gestão do patrimônio público",
    "summary": "Por Aniely Cordeiro Com o objetivo de fortalecer a gestão patrimonial no Acre, a Secretaria de Estado de Administração (Sead) realizou nesta semana o treinamento Inventário de Bens Móveis e Intangíveis. A capacitação reuniu membros de comissões e chefes de setores patrimoniais de diversos órgãos estaduais. Estes profissionais atuam diretamente na execução, controle e validação [&#8230;] The post Administração capacita servidores do Estado para fortalecer a gestão do patrimônio público appeared first on Noticias do Acre .",
    "lede": "Por Aniely Cordeiro Com o objetivo de fortalecer a gestão patrimonial no Acre, a Secretaria de Estado de Administração (Sead) realizou nesta semana o treinamento Inventário de Bens Móveis e Intangíveis. A capacitação reuniu membros de comissões e chefes de setores patrimoniais de diversos órgãos estaduais. Estes profissionais atuam diretamente na execução, controle e validação [&#8230;] The post Administração capacita servidores do Estado para fortalecer a gestão do patrimônio público appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/administracao-capacita-servidores-do-estado-para-fortalecer-a-gestao-do-patrimonio-publico/",
    "sourceUrl": "https://agencia.ac.gov.br/administracao-capacita-servidores-do-estado-para-fortalecer-a-gestao-do-patrimonio-publico/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Administração capacita servidores do Estado para fortalecer a gestão do patrimônio público",
    "category": "Prefeitura",
    "publishedAt": "2026-04-17T19:43:43.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/4fdc1a9f-0d5b-4d94-9831-076b79ad71bd-1024x768.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/4fdc1a9f-0d5b-4d94-9831-076b79ad71bd-1024x768.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/f0b85a1b-7fda-49be-a457-ecd236c93b82-1024x459.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/seagri-recebe-representantes-do-sebrae-do-rio-grande-do-norte-para-troca-de-experiencias-na-cafeicultura/",
    "slug": "seagri-recebe-representantes-do-sebrae-do-rio-grande-do-norte-para-troca-de-experiencias-na-cafeicultura",
    "title": "Seagri recebe representantes do Sebrae do Rio Grande do Norte para troca de experiências na cafeicultura",
    "summary": "O governo do Acre, por meio da Secretaria de Estado de Agricultura (Seagri), recebeu representantes do Serviço Brasileiro de Apoio às Micro e Pequenas Empresas do Rio Grande do Norte (Sebrae/RN) em uma agenda de alinhamento institucional voltada à troca de experiências sobre o desenvolvimento da cafeicultura. O encontro reuniu a atual titular da pasta [&#8230;] The post Seagri recebe representantes do Sebrae do Rio Grande do Norte para troca de experiências na cafeicultura appeared first on Noticias do Acre .",
    "lede": "O governo do Acre, por meio da Secretaria de Estado de Agricultura (Seagri), recebeu representantes do Serviço Brasileiro de Apoio às Micro e Pequenas Empresas do Rio Grande do Norte (Sebrae/RN) em uma agenda de alinhamento institucional voltada à troca de experiências sobre o desenvolvimento da cafeicultura. O encontro reuniu a atual titular da pasta [&#8230;] The post Seagri recebe representantes do Sebrae do Rio Grande do Norte para troca de experiências na cafeicultura appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/seagri-recebe-representantes-do-sebrae-do-rio-grande-do-norte-para-troca-de-experiencias-na-cafeicultura/",
    "sourceUrl": "https://agencia.ac.gov.br/seagri-recebe-representantes-do-sebrae-do-rio-grande-do-norte-para-troca-de-experiencias-na-cafeicultura/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Seagri recebe representantes do Sebrae do Rio Grande do Norte para troca de experiências na cafeicultura",
    "category": "Utilidade Pública",
    "publishedAt": "2026-04-17T19:02:52.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-08.32.08-1024x685.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-08.32.08-1024x685.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/9257632a-3762-4faf-a6bf-87a8d1687b1f-1024x683.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/policia-militar-lanca-projeto-voltado-a-educacao-de-meninos-e-homens-na-prevencao-da-violencia-contra-a-mulher-em-cruzeiro-do-sul/",
    "slug": "policia-militar-lanca-projeto-voltado-a-educacao-de-meninos-e-homens-na-prevencao-da-violencia-contra-a-mulher-em-cruzeiro-do-sul",
    "title": "Polícia Militar lança projeto voltado à educação de meninos e homens na prevenção da violência contra a mulher em Cruzeiro do Sul",
    "summary": "Com foco na conscientização, no respeito e na construção de uma cultura de paz, a Polícia Militar do Acre, por meio do núcleo da Patrulha Maria da Penha de Cruzeiro do Sul, realizou nesta sexta-feira, 17, no auditório do Ministério Público do Acre (MPAC), em Cruzeiro do Sul, o lançamento do projeto Educar para Prevenir, [&#8230;] The post Polícia Militar lança projeto voltado à educação de meninos e homens na prevenção da violência contra a mulher em Cruzeiro do Sul appeared first on Noticias do Acre .",
    "lede": "Com foco na conscientização, no respeito e na construção de uma cultura de paz, a Polícia Militar do Acre, por meio do núcleo da Patrulha Maria da Penha de Cruzeiro do Sul, realizou nesta sexta-feira, 17, no auditório do Ministério Público do Acre (MPAC), em Cruzeiro do Sul, o lançamento do projeto Educar para Prevenir, [&#8230;] The post Polícia Militar lança projeto voltado à educação de meninos e homens na prevenção da violência contra a mulher em Cruzeiro do Sul appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/policia-militar-lanca-projeto-voltado-a-educacao-de-meninos-e-homens-na-prevencao-da-violencia-contra-a-mulher-em-cruzeiro-do-sul/",
    "sourceUrl": "https://agencia.ac.gov.br/policia-militar-lanca-projeto-voltado-a-educacao-de-meninos-e-homens-na-prevencao-da-violencia-contra-a-mulher-em-cruzeiro-do-sul/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Polícia Militar lança projeto voltado à educação de meninos e homens na prevenção da violência contra a mulher em Cruzeiro do Sul",
    "category": "Educação",
    "publishedAt": "2026-04-17T18:59:58.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/4e398652-9831-4004-bc61-4caaa9bc7099-1024x683.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/4e398652-9831-4004-bc61-4caaa9bc7099-1024x683.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/9257632a-3762-4faf-a6bf-87a8d1687b1f-1024x683.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/exploracao-madeireira-recua-49-no-acre/",
    "slug": "exploracao-madeireira-recua-49-no-acre",
    "title": "Exploração madeireira recua 49% no Acre",
    "summary": "A exploração madeireira no estado do Acre apresentou uma queda significativa de 49% entre agosto de 2023 e julho de 2024, em comparação com o período anterior. Os dados são do Sistema de Monitoramento da Exploração Madeireira (Simex), desenvolvido pelo Imazon. De acordo com o levantamento, foram mapeados cerca de 5,3 mil hectares com atividade [&#8230;] The post Exploração madeireira recua 49% no Acre appeared first on Noticias do Acre .",
    "lede": "A exploração madeireira no estado do Acre apresentou uma queda significativa de 49% entre agosto de 2023 e julho de 2024, em comparação com o período anterior. Os dados são do Sistema de Monitoramento da Exploração Madeireira (Simex), desenvolvido pelo Imazon. De acordo com o levantamento, foram mapeados cerca de 5,3 mil hectares com atividade [&#8230;] The post Exploração madeireira recua 49% no Acre appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/exploracao-madeireira-recua-49-no-acre/",
    "sourceUrl": "https://agencia.ac.gov.br/exploracao-madeireira-recua-49-no-acre/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Exploração madeireira recua 49% no Acre",
    "category": "Prefeitura",
    "publishedAt": "2026-04-17T18:57:28.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2025/09/FLORESTA-PUYANAWA-01-FOTO-UESLEI-ARAUJO-1-1-1024x576.png",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2025/09/FLORESTA-PUYANAWA-01-FOTO-UESLEI-ARAUJO-1-1-1024x576.png",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-09.24.56-2-1024x771.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/pre-enem-legal-leva-auloes-presenciais-a-municipios-do-alto-acre/",
    "slug": "pre-enem-legal-leva-auloes-presenciais-a-municipios-do-alto-acre",
    "title": "Pré-Enem Legal leva aulões presenciais a municípios do Alto Acre",
    "summary": "O Pré-Enem Legal, programa da Secretaria de Estado de Educação e Cultura (SEE), dá continuidade à itinerância pelos municípios acreanos, ampliando o acesso à preparação para o Exame Nacional do Ensino Médio (Enem). Nesta semana, a equipe esteve na regional do Alto Acre, com atividades em Assis Brasil e Xapuri. A proposta do projeto é [&#8230;] The post Pré-Enem Legal leva aulões presenciais a municípios do Alto Acre appeared first on Noticias do Acre .",
    "lede": "O Pré-Enem Legal, programa da Secretaria de Estado de Educação e Cultura (SEE), dá continuidade à itinerância pelos municípios acreanos, ampliando o acesso à preparação para o Exame Nacional do Ensino Médio (Enem). Nesta semana, a equipe esteve na regional do Alto Acre, com atividades em Assis Brasil e Xapuri. A proposta do projeto é [&#8230;] The post Pré-Enem Legal leva aulões presenciais a municípios do Alto Acre appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/pre-enem-legal-leva-auloes-presenciais-a-municipios-do-alto-acre/",
    "sourceUrl": "https://agencia.ac.gov.br/pre-enem-legal-leva-auloes-presenciais-a-municipios-do-alto-acre/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Pré-Enem Legal leva aulões presenciais a municípios do Alto Acre",
    "category": "Educação",
    "publishedAt": "2026-04-17T17:44:08.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-09.24.56-2-1024x771.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-09.24.56-2-1024x771.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/12d1a7ca-edda-4363-8850-b5db99756809-1024x768.jpg"
  },
  {
    "id": "https://agencia.ac.gov.br/governo-do-acre-articula-liberacao-de-recursos-estrategicos-para-a-educacao-no-fnde/",
    "slug": "governo-do-acre-articula-liberacao-de-recursos-estrategicos-para-a-educacao-no-fnde",
    "title": "Governo do Acre articula liberação de recursos estratégicos para a educação no FNDE",
    "summary": "Para garantir a continuidade de projetos estratégicos e a melhoria da infraestrutura escolar, o governo do Acre realizou uma agenda técnica nesta quinta-feira, 16, no Fundo Nacional de Desenvolvimento da Educação (FNDE), em Brasília. A iniciativa foca na solução de entraves administrativos que dificultam o repasse de recursos federais destinados à rede estadual. A articulação [&#8230;] The post Governo do Acre articula liberação de recursos estratégicos para a educação no FNDE appeared first on Noticias do Acre .",
    "lede": "Para garantir a continuidade de projetos estratégicos e a melhoria da infraestrutura escolar, o governo do Acre realizou uma agenda técnica nesta quinta-feira, 16, no Fundo Nacional de Desenvolvimento da Educação (FNDE), em Brasília. A iniciativa foca na solução de entraves administrativos que dificultam o repasse de recursos federais destinados à rede estadual. A articulação [&#8230;] The post Governo do Acre articula liberação de recursos estratégicos para a educação no FNDE appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/governo-do-acre-articula-liberacao-de-recursos-estrategicos-para-a-educacao-no-fnde/",
    "sourceUrl": "https://agencia.ac.gov.br/governo-do-acre-articula-liberacao-de-recursos-estrategicos-para-a-educacao-no-fnde/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Governo do Acre articula liberação de recursos estratégicos para a educação no FNDE",
    "category": "Educação",
    "publishedAt": "2026-04-17T17:42:16.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/12d1a7ca-edda-4363-8850-b5db99756809-1024x768.jpg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/12d1a7ca-edda-4363-8850-b5db99756809-1024x768.jpg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-09.24.56-2-1024x771.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/procon-acre-lanca-programa-proconsciente-e-fortalece-acoes-de-sustentabilidade-diversidade-e-inclusao/",
    "slug": "procon-acre-lanca-programa-proconsciente-e-fortalece-acoes-de-sustentabilidade-diversidade-e-inclusao",
    "title": "Procon Acre lança Programa Proconsciente e fortalece ações de sustentabilidade, diversidade e inclusão",
    "summary": "O Instituto de Proteção e Defesa do Consumidor (Procon) criou um grupo de trabalho voltado à sustentabilidade e diversidade com o objetivo de implementar ações permanentes que fortaleçam a responsabilidade social, ambiental e institucional do órgão. Como resultado das primeiras reuniões do grupo, o Programa foi apresentado aos servidores. A iniciativa promoveu debates e orientações [&#8230;] The post Procon Acre lança Programa Proconsciente e fortalece ações de sustentabilidade, diversidade e inclusão appeared first on Noticias do Acre .",
    "lede": "O Instituto de Proteção e Defesa do Consumidor (Procon) criou um grupo de trabalho voltado à sustentabilidade e diversidade com o objetivo de implementar ações permanentes que fortaleçam a responsabilidade social, ambiental e institucional do órgão. Como resultado das primeiras reuniões do grupo, o Programa foi apresentado aos servidores. A iniciativa promoveu debates e orientações [&#8230;] The post Procon Acre lança Programa Proconsciente e fortalece ações de sustentabilidade, diversidade e inclusão appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/procon-acre-lanca-programa-proconsciente-e-fortalece-acoes-de-sustentabilidade-diversidade-e-inclusao/",
    "sourceUrl": "https://agencia.ac.gov.br/procon-acre-lanca-programa-proconsciente-e-fortalece-acoes-de-sustentabilidade-diversidade-e-inclusao/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Procon Acre lança Programa Proconsciente e fortalece ações de sustentabilidade, diversidade e inclusão",
    "category": "Festas & Social",
    "publishedAt": "2026-04-17T17:41:01.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-11.11.49-1024x576.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-11.11.49-1024x576.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-09.24.56-2-1024x771.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/governo-reforca-politica-de-seguranca-alimentar-em-reuniao-com-equipe-tecnica/",
    "slug": "governo-reforca-politica-de-seguranca-alimentar-em-reuniao-com-equipe-tecnica",
    "title": "Governo reforça política de segurança alimentar em reunião com equipe técnica",
    "summary": "A Secretaria de Estado de Assistência Social e Direitos Humanos (SEASDH) realizou, na manhã desta sexta-feira, 17, uma reunião com a equipe do Departamento de Segurança Alimentar e Nutricional, com o objetivo de fortalecer a política pública de segurança alimentar no âmbito do Estado. Durante o encontro, foram alinhadas estratégias voltadas à ampliação das ações [&#8230;] The post Governo reforça política de segurança alimentar em reunião com equipe técnica appeared first on Noticias do Acre .",
    "lede": "A Secretaria de Estado de Assistência Social e Direitos Humanos (SEASDH) realizou, na manhã desta sexta-feira, 17, uma reunião com a equipe do Departamento de Segurança Alimentar e Nutricional, com o objetivo de fortalecer a política pública de segurança alimentar no âmbito do Estado. Durante o encontro, foram alinhadas estratégias voltadas à ampliação das ações [&#8230;] The post Governo reforça política de segurança alimentar em reunião com equipe técnica appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/governo-reforca-politica-de-seguranca-alimentar-em-reuniao-com-equipe-tecnica/",
    "sourceUrl": "https://agencia.ac.gov.br/governo-reforca-politica-de-seguranca-alimentar-em-reuniao-com-equipe-tecnica/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Governo reforça política de segurança alimentar em reunião com equipe técnica",
    "category": "Prefeitura",
    "publishedAt": "2026-04-17T17:11:27.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-10.50.54-1024x576.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-10.50.54-1024x576.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/FOTO-2-2-1024x576.png"
  },
  {
    "id": "https://agencia.ac.gov.br/ieptec-prorroga-ate-a-proxima-sexta-inscricoes-em-cursos-tecnicos-para-servidores-da-educacao-nao-docentes/",
    "slug": "ieptec-prorroga-ate-a-proxima-sexta-inscricoes-em-cursos-tecnicos-para-servidores-da-educacao-nao-docentes",
    "title": "Ieptec prorroga até a próxima sexta inscrições em cursos técnicos para servidores da Educação não docentes",
    "summary": "Com o objetivo de ampliar as oportunidades para servidores da Educação não docentes, o governo do Acre, por meio do Instituto Estadual de Educação Profissional e Tecnológica (Ieptec), prorrogou até sexta-feira, 24, as inscrições para cursos técnicos subsequentes na modalidade de Educação a Distância (EaD) semipresencial. Estão sendo ofertadas 150 vagas, sendo 30 por curso. [&#8230;] The post Ieptec prorroga até a próxima sexta inscrições em cursos técnicos para servidores da Educação não docentes appeared first on Noticias do Acre .",
    "lede": "Com o objetivo de ampliar as oportunidades para servidores da Educação não docentes, o governo do Acre, por meio do Instituto Estadual de Educação Profissional e Tecnológica (Ieptec), prorrogou até sexta-feira, 24, as inscrições para cursos técnicos subsequentes na modalidade de Educação a Distância (EaD) semipresencial. Estão sendo ofertadas 150 vagas, sendo 30 por curso. [&#8230;] The post Ieptec prorroga até a próxima sexta inscrições em cursos técnicos para servidores da Educação não docentes appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/ieptec-prorroga-ate-a-proxima-sexta-inscricoes-em-cursos-tecnicos-para-servidores-da-educacao-nao-docentes/",
    "sourceUrl": "https://agencia.ac.gov.br/ieptec-prorroga-ate-a-proxima-sexta-inscricoes-em-cursos-tecnicos-para-servidores-da-educacao-nao-docentes/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Ieptec prorroga até a próxima sexta inscrições em cursos técnicos para servidores da Educação não docentes",
    "category": "Utilidade Pública",
    "publishedAt": "2026-04-17T17:09:58.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/FOTO-1-2-1024x576.png",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/FOTO-1-2-1024x576.png",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/FOTO-2-2-1024x576.png"
  }
];
