window.NEWS_DATA = [
  {
    "id": "https://ac24horas.com/2026/04/19/caminhao-atinge-carro-estacionado-derruba-poste-e-invade-comercio-em-rio-branco/",
    "slug": "caminhao-atinge-carro-estacionado-derruba-poste-e-invade-comercio",
    "title": "Caminhão atinge carro estacionado, derruba poste e invade comércio",
    "summary": "Um caminhão perdeu o controle, colidiu contra um veículo estacionado, derrubou um poste de energia e invadiu um estabelecimento comercial na madrugada deste domingo (19), na Estrada das Placas, no bairro Wanderley Dantas, na parte alta de Rio Branco. Segundo informações apuradas no local, o veículo, um caminhão baú de pequeno porte modelo Iveco/Daily, de [...]",
    "lede": "Um caminhão perdeu o controle, colidiu contra um veículo estacionado, derrubou um poste de energia e invadiu um estabelecimento comercial na madrugada deste domingo (19), na Estrada das Placas, no bairro Wanderley Dantas, na parte alta de Rio Branco. Segundo informações apuradas no local, o veículo, um caminhão baú de pequeno porte modelo Iveco/Daily, de [...]",
    "url": "https://ac24horas.com/2026/04/19/caminhao-atinge-carro-estacionado-derruba-poste-e-invade-comercio-em-rio-branco/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/caminhao-atinge-carro-estacionado-derruba-poste-e-invade-comercio-em-rio-branco/",
    "sourceName": "ac24horas",
    "sourceLabel": "Caminhão atinge carro estacionado, derruba poste e invade comércio",
    "category": "Utilidade Pública",
    "publishedAt": "2026-04-19T14:23:01.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-19-09-11-34-1200x690.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-19-09-11-34-1200x690.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-19-09-11-34-1200x690.jpg"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/mais-de-600-familias-saem-do-endividamento-no-acre-em-marco/",
    "slug": "mais-de-600-familias-saem-do-endividamento-no-acre-em-marco",
    "title": "Mais de 600 famílias saem do endividamento no Acre em março",
    "summary": "A Fecomércio Acre apontou queda no número de famílias endividadas no estado durante o mês de março, na contramão do cenário nacional. De acordo com o levantamento baseado na Pesquisa de Endividamento e Inadimplência do Consumidor da Confederação Nacional do Comércio de Bens, Serviços e Turismo (CNC), o Acre registrou redução de 0,4% no total [...]",
    "lede": "A Fecomércio Acre apontou queda no número de famílias endividadas no estado durante o mês de março, na contramão do cenário nacional. De acordo com o levantamento baseado na Pesquisa de Endividamento e Inadimplência do Consumidor da Confederação Nacional do Comércio de Bens, Serviços e Turismo (CNC), o Acre registrou redução de 0,4% no total [...]",
    "url": "https://ac24horas.com/2026/04/19/mais-de-600-familias-saem-do-endividamento-no-acre-em-marco/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/mais-de-600-familias-saem-do-endividamento-no-acre-em-marco/",
    "sourceName": "ac24horas",
    "sourceLabel": "Mais de 600 famílias saem do endividamento no Acre em março",
    "category": "Negócios",
    "publishedAt": "2026-04-19T14:20:49.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/03/contas-dividas-fdr-5-750x422-1.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/03/contas-dividas-fdr-5-750x422-1.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-19-09-11-34-1200x690.jpg"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/homem-em-situacao-de-rua-e-agredido-a-golpes-de-ripa-em-rio-branco/",
    "slug": "homem-em-situacao-de-rua-e-agredido-a-golpes-de-ripa-em-rio-branco",
    "title": "Homem em situação de rua é agredido a golpes de ripa em Rio Branco",
    "summary": "Um homem em situação de rua, identificado como Edilmo Inácio Pereira, de 52 anos, foi agredido a golpes de ripa em via pública na noite deste sábado (18), no Centro de Rio Branco. Segundo testemunhas, Edilmo estava dormindo na calçada quando um homem não identificado se aproximou e, em posse de uma ripa, desferiu golpes [...]",
    "lede": "Um homem em situação de rua, identificado como Edilmo Inácio Pereira, de 52 anos, foi agredido a golpes de ripa em via pública na noite deste sábado (18), no Centro de Rio Branco. Segundo testemunhas, Edilmo estava dormindo na calçada quando um homem não identificado se aproximou e, em posse de uma ripa, desferiu golpes [...]",
    "url": "https://ac24horas.com/2026/04/19/homem-em-situacao-de-rua-e-agredido-a-golpes-de-ripa-em-rio-branco/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/homem-em-situacao-de-rua-e-agredido-a-golpes-de-ripa-em-rio-branco/",
    "sourceName": "ac24horas",
    "sourceLabel": "Homem em situação de rua é agredido a golpes de ripa em Rio Branco",
    "category": "Cotidiano",
    "publishedAt": "2026-04-19T13:41:27.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-19-08-36-21-900x1200.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-19-08-36-21-900x1200.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-19-08-36-21-e1776606081892-1200x686.jpg"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/trump-diz-que-negociadores-vao-ao-paquistao-para-novas-conversas-com-o-ira/",
    "slug": "trump-diz-que-negociadores-vao-ao-paquistao-para-novas-conversas-com-o-ira",
    "title": "Trump diz que negociadores vão ao Paquistão para novas conversas com o Irã",
    "summary": "O presidente dos EUA, Donald Trump, discursa no Salão Cruzado da Casa Branca • Getty Images \" O presidente dos Estados Unidos, Donald Trump, disse em uma publicação no Truth Social neste domingo (19) que representantes irão a Islamabad, no Paquistão, \"amanhã à noite\" para negociações com o Irã. \"Estamos oferecendo um acordo muito justo e razoável, e espero que eles o aceitem porque, se não o fizerem, os Estados Unidos vão [...]",
    "lede": "O presidente dos EUA, Donald Trump, discursa no Salão Cruzado da Casa Branca • Getty Images \" O presidente dos Estados Unidos, Donald Trump, disse em uma publicação no Truth Social neste domingo (19) que representantes irão a Islamabad, no Paquistão, \"amanhã à noite\" para negociações com o Irã. \"Estamos oferecendo um acordo muito justo e razoável, e espero que eles o aceitem porque, se não o fizerem, os Estados Unidos vão [...]",
    "url": "https://ac24horas.com/2026/04/19/trump-diz-que-negociadores-vao-ao-paquistao-para-novas-conversas-com-o-ira/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/trump-diz-que-negociadores-vao-ao-paquistao-para-novas-conversas-com-o-ira/",
    "sourceName": "ac24horas",
    "sourceLabel": "Trump diz que negociadores vão ao Paquistão para novas conversas com o Irã",
    "category": "Festas & Social",
    "publishedAt": "2026-04-19T13:25:25.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/GettyImages-2268828737.webp",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/GettyImages-2268828737.webp",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/GettyImages-2268828737-1200x686.webp"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/projeto-de-r-10-milhoes-fortalece-mulheres-empreendedoras-e-agricultores-familiares-em-rondonia/",
    "slug": "projeto-de-r-10-milhoes-fortalece-mulheres-empreendedoras-e-agricultores-familiares-em-rondonia",
    "title": "Projeto de R$ 10 milhões fortalece mulheres empreendedoras e agricultores familiares em Rondônia",
    "summary": "Foi lançado em Porto Velho o projeto “Empoderando Mulheres Empreendedoras e Agricultores Familiares por meio da Bioeconomia em Rondônia”. A iniciativa conta com investimento de R$ 10 milhões do Fundo Brasil-ONU para o Desenvolvimento Sustentável da Amazônia, com apoio do Governo do Canadá. Com execução prevista para 2026 e 2027, o projeto tem foco na [...]",
    "lede": "Foi lançado em Porto Velho o projeto “Empoderando Mulheres Empreendedoras e Agricultores Familiares por meio da Bioeconomia em Rondônia”. A iniciativa conta com investimento de R$ 10 milhões do Fundo Brasil-ONU para o Desenvolvimento Sustentável da Amazônia, com apoio do Governo do Canadá. Com execução prevista para 2026 e 2027, o projeto tem foco na [...]",
    "url": "https://ac24horas.com/2026/04/19/projeto-de-r-10-milhoes-fortalece-mulheres-empreendedoras-e-agricultores-familiares-em-rondonia/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/projeto-de-r-10-milhoes-fortalece-mulheres-empreendedoras-e-agricultores-familiares-em-rondonia/",
    "sourceName": "ac24horas",
    "sourceLabel": "Projeto de R$ 10 milhões fortalece mulheres empreendedoras e agricultores familiares em Rondônia",
    "category": "Prefeitura",
    "publishedAt": "2026-04-19T13:12:57.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/RO.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/RO.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/RO-1200x686.jpg"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/autodeclaracao-impulsiona-crescimento-de-eleitores-indigenas-em-roraima/",
    "slug": "autodeclaracao-impulsiona-crescimento-de-eleitores-indigenas-em-roraima",
    "title": "Autodeclaração impulsiona crescimento de eleitores indígenas em Roraima",
    "summary": "A autodeclaração tem ampliado a visibilidade dos povos indígenas no eleitorado brasileiro. Entre março de 2024 e março de 2026, o número de eleitores que se identificam como indígenas cresceu 68% no país, segundo dados do Tribunal Superior Eleitoral (TSE). Em Roraima, o avanço também é expressivo, refletindo políticas de inclusão da Justiça Eleitoral. O [...]",
    "lede": "A autodeclaração tem ampliado a visibilidade dos povos indígenas no eleitorado brasileiro. Entre março de 2024 e março de 2026, o número de eleitores que se identificam como indígenas cresceu 68% no país, segundo dados do Tribunal Superior Eleitoral (TSE). Em Roraima, o avanço também é expressivo, refletindo políticas de inclusão da Justiça Eleitoral. O [...]",
    "url": "https://ac24horas.com/2026/04/19/autodeclaracao-impulsiona-crescimento-de-eleitores-indigenas-em-roraima/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/autodeclaracao-impulsiona-crescimento-de-eleitores-indigenas-em-roraima/",
    "sourceName": "ac24horas",
    "sourceLabel": "Autodeclaração impulsiona crescimento de eleitores indígenas em Roraima",
    "category": "Política",
    "publishedAt": "2026-04-19T13:11:00.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_6609.png",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_6609.png",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_6608-1200x806.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/mpe-pede-inelegibilidade-de-ex-prefeito-de-macapa-por-abuso-de-poder-nas-eleicoes-de-2024/",
    "slug": "mpe-pede-inelegibilidade-de-ex-prefeito-de-macapa-por-abuso-de-poder-nas-eleicoes-de-2024",
    "title": "MPE pede inelegibilidade de ex-prefeito de Macapá por abuso de poder nas eleições de 2024",
    "summary": "O Ministério Público Eleitoral (MPE) emitiu, no dia 17 de abril de 2026, parecer no âmbito de uma Ação de Investigação Judicial Eleitoral (AIJE) que apura supostas irregularidades na campanha de reeleição de 2024 em Macapá. No documento, o órgão aponta indícios de abuso de poder político e econômico, com uso da estrutura da Prefeitura [...]",
    "lede": "O Ministério Público Eleitoral (MPE) emitiu, no dia 17 de abril de 2026, parecer no âmbito de uma Ação de Investigação Judicial Eleitoral (AIJE) que apura supostas irregularidades na campanha de reeleição de 2024 em Macapá. No documento, o órgão aponta indícios de abuso de poder político e econômico, com uso da estrutura da Prefeitura [...]",
    "url": "https://ac24horas.com/2026/04/19/mpe-pede-inelegibilidade-de-ex-prefeito-de-macapa-por-abuso-de-poder-nas-eleicoes-de-2024/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/mpe-pede-inelegibilidade-de-ex-prefeito-de-macapa-por-abuso-de-poder-nas-eleicoes-de-2024/",
    "sourceName": "ac24horas",
    "sourceLabel": "MPE pede inelegibilidade de ex-prefeito de Macapá por abuso de poder nas eleições de 2024",
    "category": "Política",
    "publishedAt": "2026-04-19T13:08:57.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_6608-1200x806.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_6608-1200x806.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_6608-1200x806.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/manaus-esta-entre-as-cidades-com-mais-beneficiarios-do-gas-do-povo-aponta-governo-federal/",
    "slug": "manaus-esta-entre-as-cidades-com-mais-beneficiarios-do-gas-do-povo-aponta-governo-federal",
    "title": "Manaus está entre as cidades com mais beneficiários do Gás do Povo, aponta governo federal",
    "summary": "Manaus ocupa a quinta posição entre os municípios brasileiros com maior número de famílias atendidas pelo programa Gás do Povo em abril. Ao todo, são 198.746 beneficiários na capital amazonense, com repasse de R$ 22,6 milhões. O ranking é liderado por São Paulo (503.983 famílias), seguido por Rio de Janeiro (314.635), Fortaleza (218.953) e Salvador [...]",
    "lede": "Manaus ocupa a quinta posição entre os municípios brasileiros com maior número de famílias atendidas pelo programa Gás do Povo em abril. Ao todo, são 198.746 beneficiários na capital amazonense, com repasse de R$ 22,6 milhões. O ranking é liderado por São Paulo (503.983 famílias), seguido por Rio de Janeiro (314.635), Fortaleza (218.953) e Salvador [...]",
    "url": "https://ac24horas.com/2026/04/19/manaus-esta-entre-as-cidades-com-mais-beneficiarios-do-gas-do-povo-aponta-governo-federal/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/manaus-esta-entre-as-cidades-com-mais-beneficiarios-do-gas-do-povo-aponta-governo-federal/",
    "sourceName": "ac24horas",
    "sourceLabel": "Manaus está entre as cidades com mais beneficiários do Gás do Povo, aponta governo federal",
    "category": "Prefeitura",
    "publishedAt": "2026-04-19T13:07:44.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_6607-1200x816.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_6607-1200x816.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_6607-1200x816.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/norte-tem-menor-acesso-a-rede-de-esgoto-no-pais-aponta-ibge/",
    "slug": "norte-tem-menor-acesso-a-rede-de-esgoto-no-pais-aponta-ibge",
    "title": "Norte tem menor acesso à rede de esgoto no país, aponta IBGE",
    "summary": "A Região Norte registra o menor índice de domicílios com acesso à rede geral de esgoto no Brasil: 30,6%, segundo a Pnad Contínua divulgada pelo IBGE nesta sexta-feira (17). Na sequência aparecem Nordeste (52,4%), Centro-Oeste (66,9%), Sul (71,6%) e Sudeste (90,7%). No país, o acesso ao esgotamento sanitário por rede coletora passou de 68,1% em [...]",
    "lede": "A Região Norte registra o menor índice de domicílios com acesso à rede geral de esgoto no Brasil: 30,6%, segundo a Pnad Contínua divulgada pelo IBGE nesta sexta-feira (17). Na sequência aparecem Nordeste (52,4%), Centro-Oeste (66,9%), Sul (71,6%) e Sudeste (90,7%). No país, o acesso ao esgotamento sanitário por rede coletora passou de 68,1% em [...]",
    "url": "https://ac24horas.com/2026/04/19/norte-tem-menor-acesso-a-rede-de-esgoto-no-pais-aponta-ibge/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/norte-tem-menor-acesso-a-rede-de-esgoto-no-pais-aponta-ibge/",
    "sourceName": "ac24horas",
    "sourceLabel": "Norte tem menor acesso à rede de esgoto no país, aponta IBGE",
    "category": "Negócios",
    "publishedAt": "2026-04-19T13:06:08.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_6606-1200x852.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_6606-1200x852.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_6606-1200x852.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/medico-preso-em-manaus-por-abusos-e-mortes-sera-transferido-para-o-para/",
    "slug": "medico-preso-em-manaus-por-abusos-e-mortes-sera-transferido-para-o-para",
    "title": "Médico preso em Manaus por abusos e mortes será transferido para o Pará",
    "summary": "O cirurgião-geral Leandro Augusto de Sá, 49 anos, preso em Manaus, deve ser transferido para o Pará por determinação da Justiça. Ele foi detido na última quinta-feira (16), no bairro Alvorada, durante a operação Escudo Feminino, com atuação conjunta da Polícia Civil do Pará (PCPA) e apoio da Polícia Civil do Amazonas. Segundo as investigações, [...]",
    "lede": "O cirurgião-geral Leandro Augusto de Sá, 49 anos, preso em Manaus, deve ser transferido para o Pará por determinação da Justiça. Ele foi detido na última quinta-feira (16), no bairro Alvorada, durante a operação Escudo Feminino, com atuação conjunta da Polícia Civil do Pará (PCPA) e apoio da Polícia Civil do Amazonas. Segundo as investigações, [...]",
    "url": "https://ac24horas.com/2026/04/19/medico-preso-em-manaus-por-abusos-e-mortes-sera-transferido-para-o-para/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/medico-preso-em-manaus-por-abusos-e-mortes-sera-transferido-para-o-para/",
    "sourceName": "ac24horas",
    "sourceLabel": "Médico preso em Manaus por abusos e mortes será transferido para o Pará",
    "category": "Polícia",
    "publishedAt": "2026-04-19T13:03:55.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_6605.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/IMG_6605.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/gov-23-1200x799.jpg"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/governadora-mailza-assina-convenio-de-r-1-milhao-para-recuperacao-de-ramais-em-porto-walter/",
    "slug": "governadora-assina-convenio-de-r-1-milhao-para-recuperacao-de-ramais-em-porto-walter",
    "title": "Governadora assina convênio de R$ 1 milhão para recuperação de ramais em Porto Walter",
    "summary": "Governadora Mailza assina convênio de R$ 1 milhão para recuperação de ramais em Porto Walter. Foto: Ingrid Kelly/Secom. \" Depois de entregar obras de infraestrutura urbana e anunciar novos investimentos em Porto Walter, a governadora Mailza Assis assinou neste sábado, 18, um convênio no valor de R$ 1 milhão destinado à recuperação de ramais no município. A iniciativa busca melhorar o acesso das comunidades rurais, fortalecer o escoamento da produção agrícola e garantir melhores [...]",
    "lede": "Governadora Mailza assina convênio de R$ 1 milhão para recuperação de ramais em Porto Walter. Foto: Ingrid Kelly/Secom. \" Depois de entregar obras de infraestrutura urbana e anunciar novos investimentos em Porto Walter, a governadora Mailza Assis assinou neste sábado, 18, um convênio no valor de R$ 1 milhão destinado à recuperação de ramais no município. A iniciativa busca melhorar o acesso das comunidades rurais, fortalecer o escoamento da produção agrícola e garantir melhores [...]",
    "url": "https://ac24horas.com/2026/04/19/governadora-mailza-assina-convenio-de-r-1-milhao-para-recuperacao-de-ramais-em-porto-walter/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/governadora-mailza-assina-convenio-de-r-1-milhao-para-recuperacao-de-ramais-em-porto-walter/",
    "sourceName": "ac24horas",
    "sourceLabel": "Governadora assina convênio de R$ 1 milhão para recuperação de ramais em Porto Walter",
    "category": "Prefeitura",
    "publishedAt": "2026-04-19T12:39:22.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/gov-23-1200x799.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/gov-23-1200x799.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-15-at-09.47.50-2-1200x801.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/pt-pcdob-aliados-mais-rivais-nas-eleicoes-legislativas/",
    "slug": "pt-pcdob-aliados-mais-rivais-nas-eleicoes-legislativas",
    "title": "PT/PCdoB: aliados, mais rivais nas eleições legislativas!",
    "summary": "Apesar de formarem uma aliança política, o PT e o PCdoB protagonizam uma rivalidade de longa data quando o assunto são vagas na Assembleia Legislativa e na Câmara Federal. Essa disputa se renova a cada eleição. Nas eleições para vereador, por exemplo, o PT saiu vitorioso ao conseguir eleger André Kamai. Por outro lado, o [...]",
    "lede": "Apesar de formarem uma aliança política, o PT e o PCdoB protagonizam uma rivalidade de longa data quando o assunto são vagas na Assembleia Legislativa e na Câmara Federal. Essa disputa se renova a cada eleição. Nas eleições para vereador, por exemplo, o PT saiu vitorioso ao conseguir eleger André Kamai. Por outro lado, o [...]",
    "url": "https://ac24horas.com/2026/04/19/pt-pcdob-aliados-mais-rivais-nas-eleicoes-legislativas/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/pt-pcdob-aliados-mais-rivais-nas-eleicoes-legislativas/",
    "sourceName": "ac24horas",
    "sourceLabel": "PT/PCdoB: aliados, mais rivais nas eleições legislativas!",
    "category": "Política",
    "publishedAt": "2026-04-19T12:37:35.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-19-at-15.54.17-1200x638.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-19-at-15.54.17-1200x638.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-19-at-15.54.17-1200x638.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/resumo-do-bbb-26-hoje-madrugada-tem-discussao-entre-aliadas-sister-apreensiva-e-analise-de-juliano-floss/",
    "slug": "resumo-do-bbb-26-hoje-madrugada-tem-discussao-entre-aliadas-sister-8216-apreensiva-8217-e-analise-de-juliano-floss",
    "title": "Resumo do BBB 26 hoje: madrugada tem discussão entre aliadas, sister &#8216;apreensiva&#8217; e análise de Juliano Floss",
    "summary": "Resumo Madrugada 19/04 — Foto: Globo \" Na noite de sábado (18), o clima ficou tenso entre Ana Paula Renault e Milena após divergências sobre jogo nessa reta final. A jornalista questionou a postura da aliada, relembrando uma fala da recreadora que teria responsabilizado Juliano Floss por um erro seu no quiz da Prova do Finalista. Milena, no entanto, negou ter acusado [...]",
    "lede": "Resumo Madrugada 19/04 — Foto: Globo \" Na noite de sábado (18), o clima ficou tenso entre Ana Paula Renault e Milena após divergências sobre jogo nessa reta final. A jornalista questionou a postura da aliada, relembrando uma fala da recreadora que teria responsabilizado Juliano Floss por um erro seu no quiz da Prova do Finalista. Milena, no entanto, negou ter acusado [...]",
    "url": "https://ac24horas.com/2026/04/19/resumo-do-bbb-26-hoje-madrugada-tem-discussao-entre-aliadas-sister-apreensiva-e-analise-de-juliano-floss/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/resumo-do-bbb-26-hoje-madrugada-tem-discussao-entre-aliadas-sister-apreensiva-e-analise-de-juliano-floss/",
    "sourceName": "ac24horas",
    "sourceLabel": "Resumo do BBB 26 hoje: madrugada tem discussão entre aliadas, sister &#8216;apreensiva&#8217; e análise de Juliano Floss",
    "category": "Esporte",
    "publishedAt": "2026-04-19T12:16:19.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/sarah-aline.avif",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/sarah-aline.avif",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-16-at-21.30.31-1200x750.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/mailza-sacramenta-jessica-como-vice-na-sua-chapa/",
    "slug": "mailza-sacramenta-jessica-como-vice-na-sua-chapa",
    "title": "Mailza sacramenta Jéssica como vice na sua chapa",
    "summary": "Acabou qualquer dúvida de que a médica Jéssica Sales (MDB) será a candidata à vice-governadora na chapa ao governo de Mailza Assis (PP), ao essa declarar aos órgãos de comunicação de que o espaço é do MDB, que poderá indicar de sua vice a Jéssica ou outro nome do partido. Mailza reafirmou a aliança partidária [...]",
    "lede": "Acabou qualquer dúvida de que a médica Jéssica Sales (MDB) será a candidata à vice-governadora na chapa ao governo de Mailza Assis (PP), ao essa declarar aos órgãos de comunicação de que o espaço é do MDB, que poderá indicar de sua vice a Jéssica ou outro nome do partido. Mailza reafirmou a aliança partidária [...]",
    "url": "https://ac24horas.com/2026/04/19/mailza-sacramenta-jessica-como-vice-na-sua-chapa/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/mailza-sacramenta-jessica-como-vice-na-sua-chapa/",
    "sourceName": "ac24horas",
    "sourceLabel": "Mailza sacramenta Jéssica como vice na sua chapa",
    "category": "Prefeitura",
    "publishedAt": "2026-04-19T11:56:23.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/MAILZA-E-JESSICA_SALES-.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/MAILZA-E-JESSICA_SALES-.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/MAILZA-E-JESSICA_SALES-.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/precisamos-de-um-novo-mimdequeeutomo/",
    "slug": "precisamos-de-um-novo-mimdequeeutomo",
    "title": "Precisamos de um novo #mimdequeeutomo",
    "summary": "O Acre continua doente quando o assunto é vacinação. A cobertura vacinal contra a influenza (gripe) foi baixíssima: não ultrapassou 22% no primeiro trimestre. É um número muito aquém da meta básica de 95%. De acordo com dados da Secretaria de Informação e Saúde Digital, do Departamento de Monitoramento, Avaliação e Disseminação de Informações Estratégicas [...]",
    "lede": "O Acre continua doente quando o assunto é vacinação. A cobertura vacinal contra a influenza (gripe) foi baixíssima: não ultrapassou 22% no primeiro trimestre. É um número muito aquém da meta básica de 95%. De acordo com dados da Secretaria de Informação e Saúde Digital, do Departamento de Monitoramento, Avaliação e Disseminação de Informações Estratégicas [...]",
    "url": "https://ac24horas.com/2026/04/19/precisamos-de-um-novo-mimdequeeutomo/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/precisamos-de-um-novo-mimdequeeutomo/",
    "sourceName": "ac24horas",
    "sourceLabel": "Precisamos de um novo #mimdequeeutomo",
    "category": "Saúde",
    "publishedAt": "2026-04-19T11:48:50.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/gov-e1776599318460.webp",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/gov-e1776599318460.webp",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/213095711-km2d6r6bb5aabk44aiuilabpai-1200x799.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/saiba-como-vai-funcionar-o-cashback-da-restituicao-automatica-do-imposto-de-renda/",
    "slug": "saiba-como-vai-funcionar-o-cashback-da-restituicao-automatica-do-imposto-de-renda",
    "title": "Saiba como vai funcionar o cashback da restituição automática do Imposto de Renda",
    "summary": "Uma das maiores novidades da declaração do Imposto de Renda de 2026 vai impactar, curiosamente, pessoas que não prestaram contas ao fisco no ano passado. Trata-se da restituição automática, chamada de cashback pela própria Receita Federal. Quem não foi obrigado a declarar em 2025 e, de acordo com cálculos da Receita Federal, teve direito à [...]",
    "lede": "Uma das maiores novidades da declaração do Imposto de Renda de 2026 vai impactar, curiosamente, pessoas que não prestaram contas ao fisco no ano passado. Trata-se da restituição automática, chamada de cashback pela própria Receita Federal. Quem não foi obrigado a declarar em 2025 e, de acordo com cálculos da Receita Federal, teve direito à [...]",
    "url": "https://ac24horas.com/2026/04/19/saiba-como-vai-funcionar-o-cashback-da-restituicao-automatica-do-imposto-de-renda/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/saiba-como-vai-funcionar-o-cashback-da-restituicao-automatica-do-imposto-de-renda/",
    "sourceName": "ac24horas",
    "sourceLabel": "Saiba como vai funcionar o cashback da restituição automática do Imposto de Renda",
    "category": "Cotidiano",
    "publishedAt": "2026-04-19T11:45:58.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-18-at-07.46.29-1-1200x800.avif",
    "feedImageUrl": "https://audios.ebc.com.br/07/07d949305377e1c8887d2a9d8a32b10c.mp3?download&#038;filename=10-04-26_-_edgard_matsuki_-_ir_8_-_cashback_do_imposto_de_renda.mp3",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-18-at-07.46.29-1-1200x800.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/previsao-indica-sol-nuvens-e-chuvas-passageiras-neste-domingo-no-acre/",
    "slug": "previsao-indica-sol-nuvens-e-chuvas-passageiras-neste-domingo-no-acre",
    "title": "Previsão indica sol, nuvens e chuvas passageiras neste domingo no Acre",
    "summary": "Neste domingo, 19, o tempo deve permanecer instável em grande parte da Região Norte e áreas próximas, com predomínio de calor e presença constante de sol entre nuvens. O cenário climático é marcado por chuvas pontuais e passageiras, que podem ocorrer a qualquer momento do dia e, em algumas localidades, ganhar intensidade e provocar pancadas [...]",
    "lede": "Neste domingo, 19, o tempo deve permanecer instável em grande parte da Região Norte e áreas próximas, com predomínio de calor e presença constante de sol entre nuvens. O cenário climático é marcado por chuvas pontuais e passageiras, que podem ocorrer a qualquer momento do dia e, em algumas localidades, ganhar intensidade e provocar pancadas [...]",
    "url": "https://ac24horas.com/2026/04/19/previsao-indica-sol-nuvens-e-chuvas-passageiras-neste-domingo-no-acre/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/previsao-indica-sol-nuvens-e-chuvas-passageiras-neste-domingo-no-acre/",
    "sourceName": "ac24horas",
    "sourceLabel": "Previsão indica sol, nuvens e chuvas passageiras neste domingo no Acre",
    "category": "Cotidiano",
    "publishedAt": "2026-04-19T11:43:42.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/01/WhatsApp-Image-2026-01-16-at-21.53.44-1200x675.webp",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/01/WhatsApp-Image-2026-01-16-at-21.53.44-1200x675.webp",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-18-at-07.46.29-1-1200x800.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/rio-acre-sobe-e-atinge-1071-metros-em-rio-branco-aponta-defesa-civil/",
    "slug": "rio-acre-sobe-e-atinge-10-71-metros-em-rio-branco-aponta-defesa-civil",
    "title": "Rio Acre sobe e atinge 10,71 metros em Rio Branco, aponta Defesa Civil",
    "summary": "O nível do Rio Acre voltou a apresentar elevação no início da manhã deste domingo (19), em Rio Branco. De acordo com o boletim divulgado pela Defesa Civil Municipal, o manancial marcou 10,71 metros às 05h19, registrando tendência de alta. Apesar da elevação, não houve registro de chuva nas últimas 24 horas na capital acreana, [...]",
    "lede": "O nível do Rio Acre voltou a apresentar elevação no início da manhã deste domingo (19), em Rio Branco. De acordo com o boletim divulgado pela Defesa Civil Municipal, o manancial marcou 10,71 metros às 05h19, registrando tendência de alta. Apesar da elevação, não houve registro de chuva nas últimas 24 horas na capital acreana, [...]",
    "url": "https://ac24horas.com/2026/04/19/rio-acre-sobe-e-atinge-1071-metros-em-rio-branco-aponta-defesa-civil/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/rio-acre-sobe-e-atinge-1071-metros-em-rio-branco-aponta-defesa-civil/",
    "sourceName": "ac24horas",
    "sourceLabel": "Rio Acre sobe e atinge 10,71 metros em Rio Branco, aponta Defesa Civil",
    "category": "Cotidiano",
    "publishedAt": "2026-04-19T11:42:45.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/01/WhatsApp-Image-2026-01-27-at-15.28.07-2-1200x800.webp",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/01/WhatsApp-Image-2026-01-27-at-15.28.07-2-1200x800.webp",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-18-at-07.46.29-1-1200x800.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/mulher-fica-gravemente-ferida-e-jovem-com-escoriacoes-em-acidente-na-capital/",
    "slug": "mulher-fica-gravemente-ferida-e-jovem-com-escoriacoes-em-acidente-na-capital",
    "title": "Mulher fica gravemente ferida e jovem com escoriações em acidente na capital",
    "summary": "Ester Almeida de Oliveira, de 18 anos, ficou gravemente ferida, e Jadson Silva Marques, de 19, sofreu escoriações após um acidente de trânsito envolvendo uma motocicleta na noite deste sábado (18), na Rua Santo Afonso, bairro José Augusto, em Rio Branco. Segundo testemunhas, o casal trafegava em uma motocicleta modelo Honda CG 160 Fan, de [...]",
    "lede": "Ester Almeida de Oliveira, de 18 anos, ficou gravemente ferida, e Jadson Silva Marques, de 19, sofreu escoriações após um acidente de trânsito envolvendo uma motocicleta na noite deste sábado (18), na Rua Santo Afonso, bairro José Augusto, em Rio Branco. Segundo testemunhas, o casal trafegava em uma motocicleta modelo Honda CG 160 Fan, de [...]",
    "url": "https://ac24horas.com/2026/04/19/mulher-fica-gravemente-ferida-e-jovem-com-escoriacoes-em-acidente-na-capital/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/mulher-fica-gravemente-ferida-e-jovem-com-escoriacoes-em-acidente-na-capital/",
    "sourceName": "ac24horas",
    "sourceLabel": "Mulher fica gravemente ferida e jovem com escoriações em acidente na capital",
    "category": "Utilidade Pública",
    "publishedAt": "2026-04-19T11:41:36.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-19-at-05.59.04-1-1200x675.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-19-at-05.59.04-1-1200x675.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-19-at-05.59.05-1-1200x675.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/19/acre-tem-apenas-129-de-cobertura-com-vacina-bivalente-contra-covid-19/",
    "slug": "acre-tem-apenas-12-9-de-cobertura-com-vacina-bivalente-contra-covid-19",
    "title": "Acre tem apenas 12,9% de cobertura com vacina bivalente contra Covid-19",
    "summary": "Dados consultados pelo ac24horas neste sábado (18) junto ao painel do Ministério da Saúde revelam que o Acre ainda enfrenta baixa adesão à vacina bivalente contra a Covid-19. Segundo o levantamento atualizado, apenas 12,93% da população do estado recebeu o imunizante mais recente, voltado às variantes mais atuais do vírus. Ao todo, foram aplicadas 84.312 [...]",
    "lede": "Dados consultados pelo ac24horas neste sábado (18) junto ao painel do Ministério da Saúde revelam que o Acre ainda enfrenta baixa adesão à vacina bivalente contra a Covid-19. Segundo o levantamento atualizado, apenas 12,93% da população do estado recebeu o imunizante mais recente, voltado às variantes mais atuais do vírus. Ao todo, foram aplicadas 84.312 [...]",
    "url": "https://ac24horas.com/2026/04/19/acre-tem-apenas-129-de-cobertura-com-vacina-bivalente-contra-covid-19/",
    "sourceUrl": "https://ac24horas.com/2026/04/19/acre-tem-apenas-129-de-cobertura-com-vacina-bivalente-contra-covid-19/",
    "sourceName": "ac24horas",
    "sourceLabel": "Acre tem apenas 12,9% de cobertura com vacina bivalente contra Covid-19",
    "category": "Saúde",
    "publishedAt": "2026-04-19T11:37:42.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2025/02/vacina_dengue_07.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2025/02/vacina_dengue_07.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-19-at-05.59.04-1-1200x675.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/vozes-da-floresta-em-conquista/",
    "slug": "vozes-da-floresta-em-conquista",
    "title": "Vozes da floresta em conquista",
    "summary": "Por Francisca Arara Este 19 de abril, Dia dos Povos Indígenas, marca a nossa história, a história da nossa ancestralidade, do povo do cocar, dos povos indígenas na luta pelos seus direitos: direito aos territórios, direito de participação, direito de diálogo, o direito de ajudar na construção de uma política pública que venha a atender [...] The post Vozes da floresta em conquista appeared first on Noticias do Acre .",
    "lede": "Por Francisca Arara Este 19 de abril, Dia dos Povos Indígenas, marca a nossa história, a história da nossa ancestralidade, do povo do cocar, dos povos indígenas na luta pelos seus direitos: direito aos territórios, direito de participação, direito de diálogo, o direito de ajudar na construção de uma política pública que venha a atender [...] The post Vozes da floresta em conquista appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/vozes-da-floresta-em-conquista/",
    "sourceUrl": "https://agencia.ac.gov.br/vozes-da-floresta-em-conquista/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Vozes da floresta em conquista",
    "category": "Prefeitura",
    "publishedAt": "2026-04-19T14:23:17.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/FRANCISCA-ARARA-1@Cleiton.cinegrafista-05-1024x576.jpg",
    "feedImageUrl": "",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/FRANCISCA-ARARA-1@Cleiton.cinegrafista-05-1024x576.jpg"
  },
  {
    "id": "https://agencia.ac.gov.br/governo-do-acre-transforma-a-realidade-de-familias-atipicas-em-acrelandia/",
    "slug": "governo-do-acre-transforma-a-realidade-de-familias-atipicas-em-acrelandia",
    "title": "Governo do Acre Transforma a Realidade de Famílias Atípicas em Acrelândia",
    "summary": "Em um esforço conjunto para descentralizar a saúde e levar dignidade às famílias do interior, o governo do Estado do Acre realizou, nos dias 17 e 18 de abril, um mutirão de atendimento multidisciplinar especializado em Transtorno do Espectro Autista (TEA). A ação, coordenada pela Secretaria de Estado de Saúde (Sesacre), transformou a rotina de [...] The post Governo do Acre Transforma a Realidade de Famílias Atípicas em Acrelândia appeared first on Noticias do Acre .",
    "lede": "Em um esforço conjunto para descentralizar a saúde e levar dignidade às famílias do interior, o governo do Estado do Acre realizou, nos dias 17 e 18 de abril, um mutirão de atendimento multidisciplinar especializado em Transtorno do Espectro Autista (TEA). A ação, coordenada pela Secretaria de Estado de Saúde (Sesacre), transformou a rotina de [...] The post Governo do Acre Transforma a Realidade de Famílias Atípicas em Acrelândia appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/governo-do-acre-transforma-a-realidade-de-familias-atipicas-em-acrelandia/",
    "sourceUrl": "https://agencia.ac.gov.br/governo-do-acre-transforma-a-realidade-de-familias-atipicas-em-acrelandia/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Governo do Acre Transforma a Realidade de Famílias Atípicas em Acrelândia",
    "category": "Saúde",
    "publishedAt": "2026-04-19T14:21:32.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-18-at-16.43.56-1024x682.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-18-at-16.43.56-1024x682.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/FRANCISCA-ARARA-1@Cleiton.cinegrafista-05-1024x576.jpg"
  },
  {
    "id": "https://agencia.ac.gov.br/as-digitais-femininas-que-transformam-trajetorias-indigenas/",
    "slug": "as-digitais-femininas-que-transformam-trajetorias-indigenas",
    "title": "As digitais femininas que transformam trajetórias indígenas",
    "summary": "&#160; A história indígena não começa em 1500 nem ficou no passado. Quando os colonizadores chegaram, milhões já viviam nas Américas. Hoje, mais de 1,6 milhão de indígenas seguem presentes no Brasil, onde mantêm cantos, tradições e enfrentam disputas por existência. Nesse contexto, as mulheres são maioria, segundo o Instituto Brasileiro de Geografia e Estatística [...] The post As digitais femininas que transformam trajetórias indígenas appeared first on Noticias do Acre .",
    "lede": "&#160; A história indígena não começa em 1500 nem ficou no passado. Quando os colonizadores chegaram, milhões já viviam nas Américas. Hoje, mais de 1,6 milhão de indígenas seguem presentes no Brasil, onde mantêm cantos, tradições e enfrentam disputas por existência. Nesse contexto, as mulheres são maioria, segundo o Instituto Brasileiro de Geografia e Estatística [...] The post As digitais femininas que transformam trajetórias indígenas appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/as-digitais-femininas-que-transformam-trajetorias-indigenas/",
    "sourceUrl": "https://agencia.ac.gov.br/as-digitais-femininas-que-transformam-trajetorias-indigenas/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "As digitais femininas que transformam trajetórias indígenas",
    "category": "Prefeitura",
    "publishedAt": "2026-04-19T14:18:38.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/6-FESTIVAL_KADA-SHAWA-KAYA_SHAWADAWA@Cleiton.cinegrafista-2959-1024x574.jpg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/6-FESTIVAL_KADA-SHAWA-KAYA_SHAWADAWA@Cleiton.cinegrafista-2959-1024x574.jpg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/GEMINA_SHANENAWA@Cleiton.cinegrafista-10-1024x576.jpg"
  },
  {
    "id": "https://agencia.ac.gov.br/governo-e-instituicoes-parceiras-certificam-40-alunos-na-1a-etapa-do-projeto-pao-na-estrada/",
    "slug": "governo-e-instituicoes-parceiras-certificam-40-alunos-na-1-etapa-do-projeto-pao-na-estrada",
    "title": "Governo e instituições parceiras certificam 40 alunos na 1ª etapa do projeto Pão na Estrada",
    "summary": "O governo do Acre, por meio da Secretaria de Estado de Indústria, Ciência e Tecnologia (Seict), a Federação das Indústrias (Fieac) e o Serviço Nacional de Aprendizagem Industrial (Senai) certificaram 40 alunos na primeira etapa do projeto Pão na Estrada, voltado à qualificação profissional no setor de panificação. A solenidade foi realizada na noite de [...] The post Governo e instituições parceiras certificam 40 alunos na 1ª etapa do projeto Pão na Estrada appeared first on Noticias do Acre .",
    "lede": "O governo do Acre, por meio da Secretaria de Estado de Indústria, Ciência e Tecnologia (Seict), a Federação das Indústrias (Fieac) e o Serviço Nacional de Aprendizagem Industrial (Senai) certificaram 40 alunos na primeira etapa do projeto Pão na Estrada, voltado à qualificação profissional no setor de panificação. A solenidade foi realizada na noite de [...] The post Governo e instituições parceiras certificam 40 alunos na 1ª etapa do projeto Pão na Estrada appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/governo-e-instituicoes-parceiras-certificam-40-alunos-na-1a-etapa-do-projeto-pao-na-estrada/",
    "sourceUrl": "https://agencia.ac.gov.br/governo-e-instituicoes-parceiras-certificam-40-alunos-na-1a-etapa-do-projeto-pao-na-estrada/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Governo e instituições parceiras certificam 40 alunos na 1ª etapa do projeto Pão na Estrada",
    "category": "Utilidade Pública",
    "publishedAt": "2026-04-19T14:11:38.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-18-at-17.15.56-1024x768.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-18-at-17.15.56-1024x768.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/FRANCISCA-ARARA-1@Cleiton.cinegrafista-05-1024x576.jpg"
  },
  {
    "id": "https://agencia.ac.gov.br/parceria-entre-sine-e-iapen-fortalecera-ressocializacao-de-egressos-do-sistema-prisional-com-qualificacao-e-acesso-ao-emprego/",
    "slug": "parceria-entre-sine-e-iapen-fortalecera-ressocializacao-de-egressos-do-sistema-prisional-com-qualificacao-e-acesso-ao-emprego",
    "title": "Parceria entre Sine e Iapen fortalecerá ressocialização de egressos do sistema prisional com qualificação e acesso ao emprego",
    "summary": "O Sistema Nacional de Emprego (Sine), órgão vinculado à Secretaria de Estado de Indústria, Ciência e Tecnologia (Seict), firmou, na sexta-feira, 17, parceria com o Instituto de Administração Penitenciária (Iapen) e o Ministério do Trabalho e Emprego (MTE) para ampliar o acesso de egressos do sistema prisional ao mercado de trabalho. A iniciativa oferecerá qualificação [...] The post Parceria entre Sine e Iapen fortalecerá ressocialização de egressos do sistema prisional com qualificação e acesso ao emprego appeared first on Noticias do Acre .",
    "lede": "O Sistema Nacional de Emprego (Sine), órgão vinculado à Secretaria de Estado de Indústria, Ciência e Tecnologia (Seict), firmou, na sexta-feira, 17, parceria com o Instituto de Administração Penitenciária (Iapen) e o Ministério do Trabalho e Emprego (MTE) para ampliar o acesso de egressos do sistema prisional ao mercado de trabalho. A iniciativa oferecerá qualificação [...] The post Parceria entre Sine e Iapen fortalecerá ressocialização de egressos do sistema prisional com qualificação e acesso ao emprego appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/parceria-entre-sine-e-iapen-fortalecera-ressocializacao-de-egressos-do-sistema-prisional-com-qualificacao-e-acesso-ao-emprego/",
    "sourceUrl": "https://agencia.ac.gov.br/parceria-entre-sine-e-iapen-fortalecera-ressocializacao-de-egressos-do-sistema-prisional-com-qualificacao-e-acesso-ao-emprego/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Parceria entre Sine e Iapen fortalecerá ressocialização de egressos do sistema prisional com qualificação e acesso ao emprego",
    "category": "Prefeitura",
    "publishedAt": "2026-04-19T14:10:00.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/sine-e-iapen-parceria-1024x680.jpg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/sine-e-iapen-parceria-1024x680.jpg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/FRANCISCA-ARARA-1@Cleiton.cinegrafista-05-1024x576.jpg"
  },
  {
    "id": "https://agencia.ac.gov.br/entre-trilhas-e-rios-a-longa-jornada-de-tres-irmaos-que-enfrentam-horas-de-viagem-para-estudar-no-interior-do-acre/",
    "slug": "entre-trilhas-e-rios-a-longa-jornada-de-tres-irmaos-que-enfrentam-horas-de-viagem-para-estudar-no-interior-do-acre",
    "title": "Entre trilhas e rios, a longa jornada de três irmãos que enfrentam horas de viagem para estudar no interior do Acre",
    "summary": "Ainda é madrugada quando a rotina começa na zona rural de Bujari, no interior do Acre. Antes mesmo do sol nascer, três irmãos deixam a casa onde vivem com a família, na Fazenda Aliança, e iniciam uma jornada diária marcada por resistência, disciplina e esperança. O destino é a Escola Rural Limoeiro, localizada no km [...] The post Entre trilhas e rios, a longa jornada de três irmãos que enfrentam horas de viagem para estudar no interior do Acre appeared first on Noticias do Acre .",
    "lede": "Ainda é madrugada quando a rotina começa na zona rural de Bujari, no interior do Acre. Antes mesmo do sol nascer, três irmãos deixam a casa onde vivem com a família, na Fazenda Aliança, e iniciam uma jornada diária marcada por resistência, disciplina e esperança. O destino é a Escola Rural Limoeiro, localizada no km [...] The post Entre trilhas e rios, a longa jornada de três irmãos que enfrentam horas de viagem para estudar no interior do Acre appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/entre-trilhas-e-rios-a-longa-jornada-de-tres-irmaos-que-enfrentam-horas-de-viagem-para-estudar-no-interior-do-acre/",
    "sourceUrl": "https://agencia.ac.gov.br/entre-trilhas-e-rios-a-longa-jornada-de-tres-irmaos-que-enfrentam-horas-de-viagem-para-estudar-no-interior-do-acre/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Entre trilhas e rios, a longa jornada de três irmãos que enfrentam horas de viagem para estudar no interior do Acre",
    "category": "Educação",
    "publishedAt": "2026-04-19T14:07:52.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/IMG_6811-1024x681.jpg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/IMG_6811-1024x681.jpg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/IMG_6454-1024x681.jpg"
  },
  {
    "id": "https://agencia.ac.gov.br/endividamento-das-familias-no-acre-recua-e-governadora-atribui-resultado-a-pagamentos-em-dia-e-geracao-de-oportunidades/",
    "slug": "endividamento-das-familias-no-acre-recua-e-governadora-atribui-resultado-a-pagamentos-em-dia-e-geracao-de-oportunidades",
    "title": "Endividamento das famílias no Acre recua, e governadora atribui resultado a pagamentos em dia e geração de oportunidades",
    "summary": "Em sentido oposto ao cenário observado no restante do país, o Acre apresentou, em março, uma redução no número de famílias endividadas, de acordo com levantamento da Federação do Comércio (Fecomercio), que acompanha os indicadores econômicos locais para embasar projeções e orientar o desempenho do setor nos próximos meses. No período, o total de famílias [...] The post Endividamento das famílias no Acre recua, e governadora atribui resultado a pagamentos em dia e geração de oportunidades appeared first on Noticias do Acre .",
    "lede": "Em sentido oposto ao cenário observado no restante do país, o Acre apresentou, em março, uma redução no número de famílias endividadas, de acordo com levantamento da Federação do Comércio (Fecomercio), que acompanha os indicadores econômicos locais para embasar projeções e orientar o desempenho do setor nos próximos meses. No período, o total de famílias [...] The post Endividamento das famílias no Acre recua, e governadora atribui resultado a pagamentos em dia e geração de oportunidades appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/endividamento-das-familias-no-acre-recua-e-governadora-atribui-resultado-a-pagamentos-em-dia-e-geracao-de-oportunidades/",
    "sourceUrl": "https://agencia.ac.gov.br/endividamento-das-familias-no-acre-recua-e-governadora-atribui-resultado-a-pagamentos-em-dia-e-geracao-de-oportunidades/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Endividamento das famílias no Acre recua, e governadora atribui resultado a pagamentos em dia e geração de oportunidades",
    "category": "Prefeitura",
    "publishedAt": "2026-04-19T14:01:04.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2024/10/SINE-EMPREGO-FOTO-NETO-LUCENA-7-scaled-1-1024x683.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2024/10/SINE-EMPREGO-FOTO-NETO-LUCENA-7-scaled-1-1024x683.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2024/10/SINE-EMPREGO-FOTO-NETO-LUCENA-7-scaled-1-1024x683.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/acre-o-planejamento-de-longo-prazo-orienta-as-decisoes-e-investimentos-no-presente/",
    "slug": "acre-o-planejamento-de-longo-prazo-orienta-as-decisoes-e-investimentos-no-presente",
    "title": "Acre: o planejamento de longo prazo orienta as decisões e investimentos no presente",
    "summary": "No período de 2023 a 2025, o Governo do Estado do Acre, seguindo sua estratégia de longo prazo, cuja visão de futuro é “Acre, terra de oportunidades, socialmente justo e ambientalmente sustentável”, garantiu investimentos em pautas estruturantes, valorizando a educação, a geração de emprego e renda com investimentos em urbanização, moradia, segurança pública, agricultura e [...] The post Acre: o planejamento de longo prazo orienta as decisões e investimentos no presente appeared first on Noticias do Acre .",
    "lede": "No período de 2023 a 2025, o Governo do Estado do Acre, seguindo sua estratégia de longo prazo, cuja visão de futuro é “Acre, terra de oportunidades, socialmente justo e ambientalmente sustentável”, garantiu investimentos em pautas estruturantes, valorizando a educação, a geração de emprego e renda com investimentos em urbanização, moradia, segurança pública, agricultura e [...] The post Acre: o planejamento de longo prazo orienta as decisões e investimentos no presente appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/acre-o-planejamento-de-longo-prazo-orienta-as-decisoes-e-investimentos-no-presente/",
    "sourceUrl": "https://agencia.ac.gov.br/acre-o-planejamento-de-longo-prazo-orienta-as-decisoes-e-investimentos-no-presente/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Acre: o planejamento de longo prazo orienta as decisões e investimentos no presente",
    "category": "Prefeitura",
    "publishedAt": "2026-04-19T13:58:31.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/MAILZA-POSSE-JOSE-CAMINHA-3-683x1024.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/MAILZA-POSSE-JOSE-CAMINHA-3-683x1024.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2024/10/SINE-EMPREGO-FOTO-NETO-LUCENA-7-scaled-1-1024x683.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/saneacre-amplia-rede-de-abastecimento-e-leva-agua-potavel-para-moradores-da-travessa-torquato-no-bairro-sao-salvador-em-cruzeiro-do-sul/",
    "slug": "saneacre-amplia-rede-de-abastecimento-e-leva-agua-potavel-para-moradores-da-travessa-torquato-no-bairro-sao-salvador-em-cruzeiro-do-sul",
    "title": "Saneacre amplia rede de abastecimento e leva água potável para moradores da Travessa Torquato no bairro São Salvador em Cruzeiro do Sul",
    "summary": "Água de qualidade chegando na torneira, mais saúde no dia a dia e dignidade para centenas de pessoas. Foi assim que moradores da Travessa Torquato, no bairro São Salvador, em Cruzeiro do Sul, receberam nesta última quinta-feira, 16, a ampliação da rede de abastecimento realizada pelo Serviço de Água e Esgoto do Estado do Acre [...] The post Saneacre amplia rede de abastecimento e leva água potável para moradores da Travessa Torquato no bairro São Salvador em Cruzeiro do Sul appeared first on Noticias do Acre .",
    "lede": "Água de qualidade chegando na torneira, mais saúde no dia a dia e dignidade para centenas de pessoas. Foi assim que moradores da Travessa Torquato, no bairro São Salvador, em Cruzeiro do Sul, receberam nesta última quinta-feira, 16, a ampliação da rede de abastecimento realizada pelo Serviço de Água e Esgoto do Estado do Acre [...] The post Saneacre amplia rede de abastecimento e leva água potável para moradores da Travessa Torquato no bairro São Salvador em Cruzeiro do Sul appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/saneacre-amplia-rede-de-abastecimento-e-leva-agua-potavel-para-moradores-da-travessa-torquato-no-bairro-sao-salvador-em-cruzeiro-do-sul/",
    "sourceUrl": "https://agencia.ac.gov.br/saneacre-amplia-rede-de-abastecimento-e-leva-agua-potavel-para-moradores-da-travessa-torquato-no-bairro-sao-salvador-em-cruzeiro-do-sul/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Saneacre amplia rede de abastecimento e leva água potável para moradores da Travessa Torquato no bairro São Salvador em Cruzeiro do Sul",
    "category": "Saúde",
    "publishedAt": "2026-04-18T23:56:19.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-13.19.27-1024x768.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-17-at-13.19.27-1024x768.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-18-at-11.45.04-1024x695.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/acre-e-ucayali-reforcam-necessidade-de-integracao-em-ata-da-1a-reuniao-do-comite-de-fronteira-centro-brasil-peru/",
    "slug": "acre-e-ucayali-reforcam-necessidade-de-integracao-em-ata-da-1-reuniao-do-comite-de-fronteira-centro-brasil-peru",
    "title": "Acre e Ucayali reforçam necessidade de integração em ata da 1ª Reunião do Comitê de Fronteira Centro Brasil-Peru",
    "summary": "As delegações do Acre e de Ucayali avançaram nas discussões sobre ações conjuntas em benefício das populações da faixa de fronteira, durante a 1ª Reunião do Comitê de Fronteira Centro Brasil-Peru, realizada na cidade de Pucallpa, no departamento de Ucayali, nesta sexta-feira, 17. Ao final do encontro, uma ata foi publicada firmando intenções de compromissos [...] The post Acre e Ucayali reforçam necessidade de integração em ata da 1ª Reunião do Comitê de Fronteira Centro Brasil-Peru appeared first on Noticias do Acre .",
    "lede": "As delegações do Acre e de Ucayali avançaram nas discussões sobre ações conjuntas em benefício das populações da faixa de fronteira, durante a 1ª Reunião do Comitê de Fronteira Centro Brasil-Peru, realizada na cidade de Pucallpa, no departamento de Ucayali, nesta sexta-feira, 17. Ao final do encontro, uma ata foi publicada firmando intenções de compromissos [...] The post Acre e Ucayali reforçam necessidade de integração em ata da 1ª Reunião do Comitê de Fronteira Centro Brasil-Peru appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/acre-e-ucayali-reforcam-necessidade-de-integracao-em-ata-da-1a-reuniao-do-comite-de-fronteira-centro-brasil-peru/",
    "sourceUrl": "https://agencia.ac.gov.br/acre-e-ucayali-reforcam-necessidade-de-integracao-em-ata-da-1a-reuniao-do-comite-de-fronteira-centro-brasil-peru/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Acre e Ucayali reforçam necessidade de integração em ata da 1ª Reunião do Comitê de Fronteira Centro Brasil-Peru",
    "category": "Negócios",
    "publishedAt": "2026-04-18T21:04:17.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-18-at-11.44.59-1024x683.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-18-at-11.44.59-1024x683.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-18-at-11.45.04-1024x695.jpeg"
  }
];
